/**
 * MMO Shop VN - Dữ liệu mẫu đầy đủ
 */
const INITIAL_DATA = {
  version: "1.0",
  settings: {
    siteName: "MMO Shop VN",
    heroTitle: "Tài Nguyên MMO Số 1 Việt Nam",
    heroSubtitle: "Hơn 500+ sản phẩm đa dạng · Giao hàng tự động 24/7 · Bảo hành toàn bộ sản phẩm",
    announcementText: "🎮 Chào mừng đến MMO Shop VN | ✅ Bảo hành 7 ngày | 🚀 Giao hàng tự động 24/7 | 💎 Hơn 500 sản phẩm chất lượng | 🎁 Giảm giá lên đến 50%",
    contactFacebook: "fb.com/mmoshopvn",
    contactDiscord: "discord.gg/mmoshop",
    contactEmail: "support@mmoshop.vn",
    contactTelegram: "t.me/mmoshopvn",
    adminUsername: "admin",
    adminPassword: "admin123",
    nextProductId: 164,
    nextOrderId: 11,
    nextCategoryId: 9,
    nextUserId: 1,
    nextNotificationId: 1
  },
  users: [],
  notifications: [],
  categories: [
    { id: 1, name: "Tài khoản Game", icon: "fas fa-gamepad", color: "#e94560", slug: "tai-khoan", active: true, description: "Tài khoản game các loại đã nâng cấp sẵn" },
    { id: 2, name: "Tiền tệ Game", icon: "fas fa-coins", color: "#f5a623", slug: "tien-te", active: true, description: "Kim cương, vàng, UC, V-bucks và tiền tệ in-game" },
    { id: 3, name: "Vật phẩm / Item", icon: "fas fa-gem", color: "#00b4d8", slug: "vat-pham", active: true, description: "Skin, trang phục, vũ khí và vật phẩm hiếm" },
    { id: 4, name: "Key & Code Game", icon: "fas fa-key", color: "#06d6a0", slug: "key-code", active: true, description: "Key kích hoạt game, gift card và code ưu đãi" },
    { id: 5, name: "Nick Clone / Buff", icon: "fas fa-users", color: "#8338ec", slug: "nick-clone", active: true, description: "Tài khoản mạng xã hội, nick buff sẵn" },
    { id: 6, name: "Dịch vụ Boost", icon: "fas fa-rocket", color: "#ff6b6b", slug: "boost", active: true, description: "Dịch vụ cày thuê, leo rank và boost elo" },
    { id: 7, name: "Tool & Phần mềm", icon: "fas fa-tools", color: "#4ecdc4", slug: "tool", active: true, description: "Phần mềm hỗ trợ game, tool tự động" },
    { id: 8, name: "Thẻ nạp / Voucher", icon: "fas fa-credit-card", color: "#ffd93d", slug: "the-nap", active: true, description: "Thẻ nạp game, gift card và voucher" }
  ],
  products: [
    // ============ CATEGORY 1: Tài khoản Game ============
    { id: 1, categoryId: 1, name: "Nick LMHT - Rank Kim Cương I", description: "Tài khoản LMHT rank Kim Cương I, 85+ tướng, nhiều skin đẹp. Full bảo hành 7 ngày.", details: "• Server: Garena VN\n• Rank: Kim Cương I - 75LP\n• Số tướng: 85 tướng\n• Skin: 22 skin (3 Prestige Edition)\n• Blue Essence: 12,000\n• Full email gốc, đổi pass ngay\n• Bảo hành: 7 ngày\n• Win rate: 58%\n• Chưa từng vi phạm", price: 250000, originalPrice: 350000, stock: 8, sold: 247, rating: 4.8, reviews: 89, featured: true, hot: true, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-diamond/400/300", badge: "HOT" },
    { id: 2, categoryId: 1, name: "Nick LMHT - Rank Bạch Kim II", description: "Tài khoản LMHT rank Bạch Kim, giá tốt cho người muốn có rank sẵn.", details: "• Server: Garena VN\n• Rank: Bạch Kim II\n• Số tướng: 60 tướng\n• Skin: 10+ skin\n• Full email kèm theo\n• Bảo hành 7 ngày", price: 120000, originalPrice: 160000, stock: 15, sold: 312, rating: 4.6, reviews: 120, featured: false, hot: true, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-plat/400/300", badge: "SALE" },
    { id: 3, categoryId: 1, name: "Nick LMHT - Rank Vàng (Giá rẻ)", description: "Nick LMHT rank vàng, phù hợp người mới muốn có tài khoản rank sẵn.", details: "• Server: Garena VN\n• Rank: Vàng III\n• Số tướng: 45 tướng\n• Skin: 5+ skin\n• Bảo hành 3 ngày", price: 80000, originalPrice: 100000, stock: 25, sold: 521, rating: 4.5, reviews: 200, featured: false, hot: false, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-gold/400/300", badge: null },
    { id: 4, categoryId: 1, name: "Nick PUBG Mobile - Conqueror", description: "Tài khoản PUBG Mobile đạt Conqueror, nhiều skin súng và trang phục xịn.", details: "• Server: Global\n• Rank: Conqueror (Top 500)\n• Level: 75+\n• Skin súng: 15+ bộ\n• Outfit hiếm: 8 bộ\n• UC dư: 500\n• Full email, bảo hành 7 ngày", price: 500000, originalPrice: 700000, stock: 3, sold: 89, rating: 4.9, reviews: 45, featured: true, hot: true, active: true, game: "PUBG Mobile", image: "https://picsum.photos/seed/pubg-conq/400/300", badge: "HOT" },
    { id: 5, categoryId: 1, name: "Nick PUBG Mobile - Ace", description: "Tài khoản PUBG Mobile rank Ace, đầy đủ skin súng và trang phục.", details: "• Server: Global\n• Rank: Ace\n• Level: 60+\n• Skin súng: 8+ bộ\n• Outfit: 5 bộ\n• Bảo hành 5 ngày", price: 200000, originalPrice: 280000, stock: 7, sold: 156, rating: 4.7, reviews: 67, featured: false, hot: false, active: true, game: "PUBG Mobile", image: "https://picsum.photos/seed/pubg-ace/400/300", badge: null },
    { id: 6, categoryId: 1, name: "Nick Free Fire - Pro (Level 100+)", description: "Nick Free Fire level cao, nhiều skin súng và trang phục hiếm.", details: "• Server: VN\n• Level: 100+\n• Rank: Heroic\n• Skin súng: 12 bộ\n• Trang phục: 20+ bộ\n• Kim cương dư: 200\n• Bảo hành 7 ngày", price: 150000, originalPrice: 220000, stock: 10, sold: 298, rating: 4.6, reviews: 110, featured: true, hot: false, active: true, game: "Free Fire", image: "https://picsum.photos/seed/ff-pro/400/300", badge: "SALE" },
    { id: 7, categoryId: 1, name: "Nick Genshin Impact - AR55 Full 5★", description: "Tài khoản Genshin Impact AR55, nhiều nhân vật 5 sao, vũ khí 5 sao đầy đủ.", details: "• Server: Asia\n• AR: 55\n• Nhân vật 5★: Hu Tao, Raiden, Zhongli, Kazuha, Ganyu\n• Vũ khí 5★: 4 cây\n• Primogem dư: 5000\n• Full email Hoyoverse\n• Bảo hành 7 ngày", price: 800000, originalPrice: 1200000, stock: 2, sold: 45, rating: 5.0, reviews: 28, featured: true, hot: true, active: true, game: "Genshin Impact", image: "https://picsum.photos/seed/genshin55/400/300", badge: "VIP" },
    { id: 8, categoryId: 1, name: "Nick Genshin Impact - AR45 Starter", description: "Nick Genshin Impact AR45, có sẵn nhân vật 5 sao tốt, giá phải chăng.", details: "• Server: Asia\n• AR: 45\n• Nhân vật 5★: 2 nhân vật\n• Primogem dư: 2000\n• Bảo hành 3 ngày", price: 300000, originalPrice: 400000, stock: 5, sold: 88, rating: 4.7, reviews: 40, featured: false, hot: false, active: true, game: "Genshin Impact", image: "https://picsum.photos/seed/genshin45/400/300", badge: null },
    { id: 9, categoryId: 1, name: "Nick Valorant - Rank Immortal", description: "Tài khoản Valorant rank Immortal, nhiều skin súng xịn và đẹp.", details: "• Server: SEA\n• Rank: Immortal 2\n• Skin: Vandal Oni, Phantom RGX, Spectre Glitchpop\n• Agent đầy đủ\n• Full email, bảo hành 7 ngày", price: 450000, originalPrice: 600000, stock: 4, sold: 67, rating: 4.8, reviews: 35, featured: true, hot: true, active: true, game: "Valorant", image: "https://picsum.photos/seed/valorant-imm/400/300", badge: "HOT" },
    { id: 10, categoryId: 1, name: "Nick CS2 - Prime Status MG2", description: "Tài khoản CS2 Prime Status, rank MG2+, nhiều giờ chơi và skin đẹp.", details: "• Rank: Master Guardian 2\n• Giờ chơi: 500+\n• Prime Status: Có\n• Skins: AK-47 Red Line, M4A1-S Hyper Beast\n• Bảo hành 5 ngày", price: 200000, originalPrice: 250000, stock: 8, sold: 134, rating: 4.5, reviews: 56, featured: false, hot: false, active: true, game: "Counter-Strike 2", image: "https://picsum.photos/seed/cs2prime/400/300", badge: null },
    { id: 11, categoryId: 1, name: "Nick Clash of Clans - TH15 Max", description: "Tài khoản CoC Town Hall 15 đã max, hội tiếng tốt, anh hùng level cao.", details: "• Town Hall: 15 (90% max)\n• Builder Hall: 10\n• Trophies: 5000+\n• Hero level: BK 75, AQ 75, GW 55, RC 30\n• Bảo hành 7 ngày", price: 1200000, originalPrice: 1800000, stock: 2, sold: 23, rating: 5.0, reviews: 18, featured: true, hot: false, active: true, game: "Clash of Clans", image: "https://picsum.photos/seed/coc-th15/400/300", badge: "VIP" },
    { id: 12, categoryId: 1, name: "Nick Mobile Legends - Mythic Glory", description: "Tài khoản MLBB rank Mythic Glory, nhiều skin Legend và Collector.", details: "• Server: SEA\n• Rank: Mythic Glory\n• Skin Collector: 3\n• Skin Legend: 8\n• Hero: 120+\n• Bảo hành 7 ngày", price: 350000, originalPrice: 500000, stock: 6, sold: 189, rating: 4.7, reviews: 78, featured: false, hot: true, active: true, game: "Mobile Legends", image: "https://picsum.photos/seed/mlbb-myth/400/300", badge: "HOT" },
    { id: 13, categoryId: 1, name: "Nick Minecraft Java Edition", description: "Tài khoản Minecraft Java Edition chính chủ, đổi tên được, vào Hypixel.", details: "• Phiên bản: Java Edition\n• Có thể đổi username\n• Hỗ trợ Hypixel\n• Full Microsoft Account\n• Bảo hành 14 ngày", price: 180000, originalPrice: 220000, stock: 12, sold: 267, rating: 4.6, reviews: 98, featured: false, hot: false, active: true, game: "Minecraft", image: "https://picsum.photos/seed/minecraft-j/400/300", badge: null },
    { id: 14, categoryId: 1, name: "Nick Roblox - Premium + 5000 Robux", description: "Tài khoản Roblox Premium, nhiều Robux và item Limited hiếm.", details: "• Premium: Còn 8 tháng\n• Robux dư: 5000\n• Item Limited: 3\n• Level: 50+\n• Bảo hành 7 ngày", price: 250000, originalPrice: 350000, stock: 5, sold: 123, rating: 4.8, reviews: 55, featured: true, hot: false, active: true, game: "Roblox", image: "https://picsum.photos/seed/roblox-prem/400/300", badge: null },
    { id: 15, categoryId: 1, name: "Nick Steam - 50+ Game / 500h", description: "Tài khoản Steam nhiều game, 500+ giờ chơi, nhiều thành tích và badge.", details: "• Games: 50+ tựa game\n• Giờ chơi: 500+\n• Điểm Steam: 3000+\n• Badge: 20+\n• Level Steam: 30+\n• Bảo hành 7 ngày", price: 350000, originalPrice: 480000, stock: 4, sold: 78, rating: 4.7, reviews: 34, featured: false, hot: false, active: true, game: "Steam", image: "https://picsum.photos/seed/steam500h/400/300", badge: null },
    // ============ CATEGORY 2: Tiền tệ Game ============
    { id: 16, categoryId: 2, name: "Kim Cương Free Fire - 1000 KCM", description: "Nạp 1000 kim cương Free Fire trực tiếp vào tài khoản của bạn.", details: "• Số lượng: 1000 Kim Cương\n• Nạp trực tiếp vào UID\n• Thời gian: 5-15 phút\n• Cần cung cấp: UID + Server\n• Hỗ trợ 24/7", price: 200000, originalPrice: 230000, stock: 999, sold: 1523, rating: 4.9, reviews: 456, featured: true, hot: true, active: true, game: "Free Fire", image: "https://picsum.photos/seed/ff-kc1000/400/300", badge: "HOT" },
    { id: 17, categoryId: 2, name: "Kim Cương Free Fire - 520 KCM", description: "Nạp 520 kim cương Free Fire, tiết kiệm so với nạp trực tiếp.", details: "• Số lượng: 520 Kim Cương\n• Nạp trực tiếp vào UID\n• Thời gian: 5-15 phút\n• Cần cung cấp: UID", price: 110000, originalPrice: 130000, stock: 999, sold: 2341, rating: 4.9, reviews: 789, featured: false, hot: true, active: true, game: "Free Fire", image: "https://picsum.photos/seed/ff-kc520/400/300", badge: "HOT" },
    { id: 18, categoryId: 2, name: "V-Bucks Fortnite - 2800 VB", description: "Gói 2800 V-Bucks cho Fortnite, mua skin Battle Royale và Battle Pass.", details: "• Số lượng: 2800 V-Bucks\n• Platform: PC/Console/Mobile\n• Thời gian: 15-30 phút\n• Cần: Epic Games ID", price: 320000, originalPrice: 380000, stock: 999, sold: 567, rating: 4.8, reviews: 234, featured: false, hot: false, active: true, game: "Fortnite", image: "https://picsum.photos/seed/fortnite-vb/400/300", badge: null },
    { id: 19, categoryId: 2, name: "Robux Roblox - 2000 R$", description: "2000 Robux cho tài khoản Roblox, mua gamepass và item trong game.", details: "• Số lượng: 2000 Robux\n• Qua Gift Card/Group Payout\n• Thời gian: 5-10 phút\n• Cần: Roblox Username", price: 250000, originalPrice: 290000, stock: 999, sold: 890, rating: 4.8, reviews: 345, featured: true, hot: true, active: true, game: "Roblox", image: "https://picsum.photos/seed/roblox-robux/400/300", badge: "HOT" },
    { id: 20, categoryId: 2, name: "UC PUBG Mobile - 1875 UC", description: "1875 UC cho PUBG Mobile, mua skin súng và outfit xịn.", details: "• Số lượng: 1875 UC\n• Nạp trực tiếp vào UID\n• Thời gian: 5-15 phút\n• Cần: Character ID", price: 300000, originalPrice: 350000, stock: 999, sold: 1234, rating: 4.9, reviews: 456, featured: true, hot: true, active: true, game: "PUBG Mobile", image: "https://picsum.photos/seed/pubg-uc/400/300", badge: "HOT" },
    { id: 21, categoryId: 2, name: "Riot Points LMHT - 1380 RP", description: "1380 RP cho Liên Minh Huyền Thoại, mua skin và champion mới.", details: "• Số lượng: 1380 RP\n• Server: Garena VN\n• Thời gian: 5-10 phút\n• Cần: Summoner Name", price: 150000, originalPrice: 170000, stock: 999, sold: 2100, rating: 4.9, reviews: 678, featured: false, hot: false, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-rp1380/400/300", badge: null },
    { id: 22, categoryId: 2, name: "Gems Clash of Clans - 1200", description: "1200 Gems cho Clash of Clans, tăng tốc xây dựng và mua builder.", details: "• Số lượng: 1200 Gems\n• Nạp qua Gift Card\n• Thời gian: 10-15 phút", price: 200000, originalPrice: 240000, stock: 999, sold: 678, rating: 4.7, reviews: 234, featured: false, hot: false, active: true, game: "Clash of Clans", image: "https://picsum.photos/seed/coc-gems/400/300", badge: null },
    { id: 23, categoryId: 2, name: "Primogem Genshin Impact - 6480", description: "6480 Primogem cho Genshin Impact, kéo gacha nhân vật mới.", details: "• Số lượng: 6480 Primogem\n• Server: Asia\n• Thời gian: 10-20 phút\n• Cần: UID Genshin", price: 500000, originalPrice: 620000, stock: 999, sold: 345, rating: 4.8, reviews: 156, featured: true, hot: false, active: true, game: "Genshin Impact", image: "https://picsum.photos/seed/genshin-primo/400/300", badge: null },
    { id: 24, categoryId: 2, name: "Gold World of Warcraft - 100K", description: "100,000 Gold cho World of Warcraft, mua đồ và dịch vụ in-game.", details: "• Số lượng: 100,000 Gold\n• Server: EU/US\n• Thời gian: 1-2 giờ\n• Giao qua Trade", price: 400000, originalPrice: 500000, stock: 50, sold: 145, rating: 4.6, reviews: 67, featured: false, hot: false, active: true, game: "World of Warcraft", image: "https://picsum.photos/seed/wow-gold/400/300", badge: null },
    { id: 25, categoryId: 2, name: "Zeny Ragnarok Origin - 50M", description: "50 triệu Zeny cho Ragnarok Origin, mua trang bị mạnh mẽ.", details: "• Số lượng: 50,000,000 Zeny\n• Server: SEA\n• Thời gian: 30-60 phút\n• Giao qua Mail In-game", price: 180000, originalPrice: 220000, stock: 100, sold: 234, rating: 4.7, reviews: 89, featured: false, hot: false, active: true, game: "Ragnarok Origin", image: "https://picsum.photos/seed/ro-zeny/400/300", badge: null },
    // ============ CATEGORY 3: Vật phẩm / Item ============
    { id: 26, categoryId: 3, name: "Skin LMHT - Prestige Edition", description: "Skin Prestige Edition hiếm cho Liên Minh Huyền Thoại, bao gồm chroma.", details: "• Tướng: Theo lựa chọn\n• Loại: Prestige Edition\n• Bao gồm: Chromas + Icon\n• Giao qua account\n• Bảo hành: Trong game", price: 350000, originalPrice: 500000, stock: 10, sold: 89, rating: 4.9, reviews: 45, featured: true, hot: true, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-prestige/400/300", badge: "HIẾM" },
    { id: 27, categoryId: 3, name: "Skin Valorant - Phantom RGX 2.0", description: "Skin Phantom RGX 11z Pro 2.0 cực sang chảnh cho Valorant.", details: "• Vũ khí: Phantom\n• Bundle: RGX 11z Pro 2.0\n• Bao gồm: Kill banner + Gun buddy\n• Giao qua account riêng", price: 280000, originalPrice: 380000, stock: 8, sold: 67, rating: 4.8, reviews: 34, featured: false, hot: true, active: true, game: "Valorant", image: "https://picsum.photos/seed/val-rgx/400/300", badge: "HOT" },
    { id: 28, categoryId: 3, name: "Nhân vật C6 Hu Tao - Genshin", description: "Nhân vật Hu Tao C6 hoàn chỉnh kèm vũ khí Staff of Homa trong Genshin Impact.", details: "• Nhân vật: Hu Tao\n• Constellation: C6\n• Vũ khí: Staff of Homa R1\n• Artifact: 4 Shimenawa full set\n• Giao qua account\n• Bảo hành 7 ngày", price: 2000000, originalPrice: 3000000, stock: 2, sold: 12, rating: 5.0, reviews: 8, featured: true, hot: false, active: true, game: "Genshin Impact", image: "https://picsum.photos/seed/genshin-hutao/400/300", badge: "VIP" },
    { id: 29, categoryId: 3, name: "Pet Shadow Dragon - Roblox Adopt Me", description: "Shadow Dragon - pet cực hiếm trong Adopt Me Roblox.", details: "• Game: Adopt Me (Roblox)\n• Pet: Shadow Dragon\n• Neon: Không\n• Giao qua Trade in-game", price: 150000, originalPrice: 200000, stock: 5, sold: 45, rating: 4.8, reviews: 20, featured: false, hot: false, active: true, game: "Roblox - Adopt Me", image: "https://picsum.photos/seed/roblox-shadow/400/300", badge: "HIẾM" },
    { id: 30, categoryId: 3, name: "Skin M416 Glacier - PUBG Mobile", description: "Skin súng M416 Glacier cực đẹp và hiếm trong PUBG Mobile.", details: "• Súng: M416\n• Skin: Glacier (Legendary)\n• Giao qua account\n• Bảo hành 3 ngày", price: 200000, originalPrice: 280000, stock: 6, sold: 78, rating: 4.7, reviews: 35, featured: false, hot: true, active: true, game: "PUBG Mobile", image: "https://picsum.photos/seed/pubg-glacier/400/300", badge: "HOT" },
    { id: 31, categoryId: 3, name: "Tướng Jinx + 5 Skin Bundle LMHT", description: "Tướng Jinx kèm 5 skin đẹp nhất, bao gồm Arcane Jinx và Star Guardian.", details: "• Tướng: Jinx\n• Skin: Arcane, Star Guardian, Ambitious Elf, Slayer, Firecracker\n• Giao qua account\n• Bảo hành 3 ngày", price: 180000, originalPrice: 250000, stock: 10, sold: 134, rating: 4.7, reviews: 58, featured: false, hot: false, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-jinx/400/300", badge: null },
    { id: 32, categoryId: 3, name: "Outfit FF Pro League 2024", description: "Trang phục Pro League 2024 độc quyền trong Free Fire.", details: "• Set: Pro League Full Set\n• Bao gồm: Áo + Quần + Giày + Mũ\n• Hiệu ứng đặc biệt\n• Giao qua account", price: 250000, originalPrice: 350000, stock: 4, sold: 56, rating: 4.8, reviews: 25, featured: false, hot: false, active: true, game: "Free Fire", image: "https://picsum.photos/seed/ff-outfit/400/300", badge: null },
    { id: 33, categoryId: 3, name: "Thẻ Legendary Clash Royale x5", description: "5 thẻ Legendary hiếm trong Clash Royale để đổi lấy thẻ bài.", details: "• Loại: Legendary Card\n• Số lượng: 5 thẻ\n• Trao đổi qua: Clan Trading\n• Server: Global", price: 120000, originalPrice: 160000, stock: 20, sold: 89, rating: 4.6, reviews: 40, featured: false, hot: false, active: true, game: "Clash Royale", image: "https://picsum.photos/seed/cr-legend/400/300", badge: null },
    // ============ CATEGORY 4: Key & Code ============
    { id: 34, categoryId: 4, name: "Key Windows 11 Pro - Vĩnh viễn", description: "Key kích hoạt Windows 11 Professional bản quyền vĩnh viễn, 1 máy tính.", details: "• Version: Windows 11 Pro\n• Loại: OEM/Retail\n• Kích hoạt: 1 máy tính\n• Hỗ trợ: Update vĩnh viễn\n• Giao ngay qua email\n• Bảo hành: Không hết hạn", price: 150000, originalPrice: 200000, stock: 999, sold: 1234, rating: 4.8, reviews: 567, featured: true, hot: true, active: true, game: "Microsoft Windows", image: "https://picsum.photos/seed/win11key/400/300", badge: "HOT" },
    { id: 35, categoryId: 4, name: "Key Microsoft Office 365 - 1 Năm", description: "Key Office 365 Personal, bao gồm Word, Excel, PowerPoint, OneDrive 1TB.", details: "• Gói: Office 365 Personal\n• Thời hạn: 1 năm\n• Bao gồm: Word, Excel, PowerPoint, Outlook, OneDrive 1TB\n• Kích hoạt: 1 máy\n• Giao qua email", price: 200000, originalPrice: 280000, stock: 999, sold: 789, rating: 4.8, reviews: 345, featured: true, hot: false, active: true, game: "Microsoft Office", image: "https://picsum.photos/seed/office365/400/300", badge: null },
    { id: 36, categoryId: 4, name: "Key Steam Random Game AAA", description: "Key ngẫu nhiên game AAA trên Steam, đảm bảo giá trị tối thiểu $20.", details: "• Nền tảng: Steam\n• Thể loại: AAA Game ngẫu nhiên\n• Giá trị tối thiểu: $20\n• Giao qua email ngay lập tức", price: 50000, originalPrice: 80000, stock: 999, sold: 2345, rating: 4.3, reviews: 890, featured: false, hot: true, active: true, game: "Steam", image: "https://picsum.photos/seed/steam-aaa/400/300", badge: "HOT" },
    { id: 37, categoryId: 4, name: "Key Discord Nitro - 1 Tháng", description: "Discord Nitro 1 tháng, mở khóa emoji tùy chỉnh, boost server.", details: "• Dịch vụ: Discord Nitro\n• Thời hạn: 1 tháng\n• Bao gồm: Custom emoji, server boost, 100MB upload\n• Giao ngay qua Discord link", price: 80000, originalPrice: 110000, stock: 999, sold: 567, rating: 4.7, reviews: 234, featured: false, hot: false, active: true, game: "Discord", image: "https://picsum.photos/seed/discord-nitro/400/300", badge: null },
    { id: 38, categoryId: 4, name: "Xbox Game Pass Ultimate - 1 Tháng", description: "Xbox Game Pass Ultimate cho phép chơi 100+ game trên Xbox và PC.", details: "• Dịch vụ: Xbox Game Pass Ultimate\n• Thời hạn: 1 tháng\n• Bao gồm: 100+ game, Xbox Live Gold, EA Play\n• Giao ngay qua email", price: 180000, originalPrice: 250000, stock: 999, sold: 345, rating: 4.7, reviews: 156, featured: false, hot: false, active: true, game: "Xbox", image: "https://picsum.photos/seed/xbox-gamepass/400/300", badge: null },
    { id: 39, categoryId: 4, name: "Steam Gift Card - 200,000 VNĐ", description: "Thẻ quà tặng Steam 200,000 VNĐ để mua game yêu thích.", details: "• Giá trị: 200,000 VNĐ\n• Dùng tại: Steam Store\n• Giao ngay qua email\n• Không có ngày hết hạn", price: 210000, originalPrice: 220000, stock: 999, sold: 1234, rating: 4.9, reviews: 456, featured: false, hot: false, active: true, game: "Steam", image: "https://picsum.photos/seed/steam-gift/400/300", badge: null },
    { id: 40, categoryId: 4, name: "Key Kaspersky Total Security - 1Y", description: "Bản quyền Kaspersky Total Security 1 máy tính - 1 năm bảo vệ toàn diện.", details: "• Phần mềm: Kaspersky Total Security\n• Thời hạn: 1 năm\n• Thiết bị: 1 PC/Mac\n• Giao ngay qua email", price: 120000, originalPrice: 180000, stock: 999, sold: 456, rating: 4.6, reviews: 189, featured: false, hot: false, active: true, game: "Kaspersky", image: "https://picsum.photos/seed/kaspersky/400/300", badge: "SALE" },
    { id: 41, categoryId: 4, name: "Netflix Premium - 1 Tháng 4K", description: "Tài khoản Netflix Premium 1 tháng, xem phim 4K UHD không giới hạn.", details: "• Gói: Premium (4 màn hình)\n• Chất lượng: 4K UHD\n• Thời hạn: 1 tháng\n• Giao qua email", price: 90000, originalPrice: 120000, stock: 999, sold: 2345, rating: 4.7, reviews: 789, featured: true, hot: true, active: true, game: "Netflix", image: "https://picsum.photos/seed/netflix/400/300", badge: "HOT" },
    // ============ CATEGORY 5: Nick Clone / Buff ============
    { id: 42, categoryId: 5, name: "Nick Facebook Clone - Chuẩn BM", description: "Facebook clone đã xác minh, có thể tạo Business Manager ngay.", details: "• Loại: Clone chuẩn\n• Xác minh: SĐT hoặc Email\n• Business Manager: Tạo được\n• Tuổi: 3-6 tháng\n• Kèm cookies\n• Bảo hành 3 ngày", price: 50000, originalPrice: 70000, stock: 100, sold: 1234, rating: 4.5, reviews: 456, featured: true, hot: true, active: true, game: "Facebook", image: "https://picsum.photos/seed/fb-clone/400/300", badge: "HOT" },
    { id: 43, categoryId: 5, name: "Gmail Account - Buff Sẵn", description: "Tài khoản Gmail đã hoạt động, phù hợp cho các dịch vụ MMO.", details: "• Loại: Gmail chuẩn\n• Xác minh: SĐT\n• Tuổi: 1-3 tháng\n• Recovery email: Có\n• Bảo hành 3 ngày", price: 30000, originalPrice: 45000, stock: 200, sold: 2345, rating: 4.4, reviews: 789, featured: false, hot: true, active: true, game: "Gmail/Google", image: "https://picsum.photos/seed/gmail-buff/400/300", badge: "HOT" },
    { id: 44, categoryId: 5, name: "TikTok Account - 1000 Followers", description: "Tài khoản TikTok với 1000+ followers thật, phù hợp seeding nội dung.", details: "• Followers: 1000+\n• Following: 500\n• Video: 20+\n• Tương tác: Tốt\n• Bảo hành 7 ngày", price: 80000, originalPrice: 120000, stock: 50, sold: 345, rating: 4.5, reviews: 134, featured: false, hot: false, active: true, game: "TikTok", image: "https://picsum.photos/seed/tiktok-1k/400/300", badge: null },
    { id: 45, categoryId: 5, name: "Instagram Account - Niche Sẵn", description: "Tài khoản Instagram đã có niche, followers và engagement tốt.", details: "• Followers: 500+\n• Niche: Fashion/Food/Gaming\n• Engagement rate: 5%+\n• Bảo hành 7 ngày", price: 45000, originalPrice: 60000, stock: 80, sold: 456, rating: 4.3, reviews: 178, featured: false, hot: false, active: true, game: "Instagram", image: "https://picsum.photos/seed/ig-niche/400/300", badge: null },
    { id: 46, categoryId: 5, name: "YouTube Channel - Monetize Ready", description: "Kênh YouTube đã đủ điều kiện monetize (1000 sub + 4000h watch time).", details: "• Subscribers: 1000+\n• Watch hours: 4000+\n• Trạng thái: Đủ điều kiện monetize\n• Nội dung: Sạch\n• Bảo hành 14 ngày", price: 500000, originalPrice: 800000, stock: 5, sold: 34, rating: 4.9, reviews: 20, featured: true, hot: false, active: true, game: "YouTube", image: "https://picsum.photos/seed/youtube-mono/400/300", badge: "VIP" },
    { id: 47, categoryId: 5, name: "Twitter/X Account - Verified Look", description: "Tài khoản Twitter tuổi cao, ảnh đại diện và bio đầy đủ.", details: "• Tuổi: 2+ năm\n• Followers: 200+\n• 2FA: Có\n• Phone verified\n• Bảo hành 3 ngày", price: 60000, originalPrice: 80000, stock: 60, sold: 234, rating: 4.4, reviews: 98, featured: false, hot: false, active: true, game: "Twitter/X", image: "https://picsum.photos/seed/twitter-x/400/300", badge: null },
    // ============ CATEGORY 6: Dịch vụ Boost ============
    { id: 48, categoryId: 6, name: "Boost LMHT - Vàng → Kim Cương", description: "Dịch vụ leo rank từ Vàng lên Kim Cương trong LMHT, an toàn và uy tín.", details: "• Từ: Vàng I\n• Đến: Kim Cương IV\n• Phương thức: Boost kèm hoặc tự boosting\n• Thời gian: 5-7 ngày\n• VPN bảo vệ tài khoản\n• Bảo mật 100%", price: 500000, originalPrice: 700000, stock: 10, sold: 145, rating: 4.8, reviews: 78, featured: true, hot: true, active: true, game: "Liên Minh Huyền Thoại", image: "https://picsum.photos/seed/lol-boost/400/300", badge: "HOT" },
    { id: 49, categoryId: 6, name: "Boost Valorant - Lên Immortal", description: "Dịch vụ leo rank Valorant lên Immortal, đảm bảo kết quả.", details: "• Từ: Diamond I trở lên\n• Đến: Immortal\n• Thời gian: 3-5 ngày\n• Win rate cam kết: 70%+\n• Bảo mật tuyệt đối", price: 600000, originalPrice: 850000, stock: 8, sold: 89, rating: 4.8, reviews: 45, featured: false, hot: true, active: true, game: "Valorant", image: "https://picsum.photos/seed/val-boost/400/300", badge: "HOT" },
    { id: 50, categoryId: 6, name: "Boost PUBG - Lên Conqueror", description: "Dịch vụ leo rank PUBG Mobile lên Conqueror - đỉnh cao rank mùa.", details: "• Từ: Ace (hoặc thấp hơn)\n• Đến: Conqueror\n• Thời gian: 7-14 ngày\n• Báo cáo tiến độ mỗi ngày", price: 800000, originalPrice: 1100000, stock: 5, sold: 56, rating: 4.9, reviews: 34, featured: true, hot: false, active: true, game: "PUBG Mobile", image: "https://picsum.photos/seed/pubg-boost/400/300", badge: null },
    { id: 51, categoryId: 6, name: "Cày thuê Free Fire - Pass Ranked", description: "Dịch vụ cày rank Free Fire theo số điểm yêu cầu.", details: "• Dịch vụ: Cày điểm ranked\n• Đơn giá: 1000 điểm = 200k\n• Thời gian: Tùy rank\n• Báo cáo hàng ngày", price: 200000, originalPrice: 250000, stock: 15, sold: 234, rating: 4.6, reviews: 95, featured: false, hot: false, active: true, game: "Free Fire", image: "https://picsum.photos/seed/ff-boost/400/300", badge: null },
    { id: 52, categoryId: 6, name: "Boost Mobile Legends - Epic → Mythic", description: "Leo rank MLBB từ Epic lên Mythic cùng pro player, duo boost.", details: "• Từ: Epic\n• Đến: Mythic\n• Thời gian: 5-8 ngày\n• Phương thức: Duo boost\n• Win rate: 65%+", price: 350000, originalPrice: 500000, stock: 10, sold: 178, rating: 4.7, reviews: 67, featured: false, hot: true, active: true, game: "Mobile Legends", image: "https://picsum.photos/seed/mlbb-boost/400/300", badge: "HOT" },
    { id: 53, categoryId: 6, name: "Boost WoW - Mythic+ Dungeon Key 15", description: "Run Mythic+ 15 cho World of Warcraft, nhận loot ilvl xịn.", details: "• Dungeon: Theo yêu cầu\n• Key level: +15\n• Loot: Trading có thể\n• Thời gian: 30-45 phút\n• Cần: ilvl 400+", price: 1000000, originalPrice: 1500000, stock: 3, sold: 23, rating: 5.0, reviews: 15, featured: false, hot: false, active: true, game: "World of Warcraft", image: "https://picsum.photos/seed/wow-boost/400/300", badge: "VIP" },
    // ============ CATEGORY 7: Tool & Phần mềm ============
    { id: 54, categoryId: 7, name: "Tool Auto Farm Game Mobile", description: "Phần mềm tự động farm tài nguyên trong game mobile đa năng.", details: "• Hỗ trợ: 10+ game mobile\n• Tính năng: Auto click, auto farm, auto quests\n• Platform: Android (BlueStacks)\n• Cập nhật: Miễn phí vĩnh viễn\n• Hỗ trợ: Chat 24/7", price: 300000, originalPrice: 450000, stock: 999, sold: 345, rating: 4.5, reviews: 156, featured: true, hot: false, active: true, game: "Mobile Games", image: "https://picsum.photos/seed/tool-farm/400/300", badge: null },
    { id: 55, categoryId: 7, name: "Bot Discord MMO - All in One", description: "Bot Discord quản lý server MMO với shop, rank, ticket và nhiều tính năng.", details: "• Tính năng: Shop bot, rank, ticket, welcome, logs\n• Cài vào server của bạn\n• Dashboard quản lý web\n• Hỗ trợ 24/7\n• Cập nhật định kỳ", price: 200000, originalPrice: 300000, stock: 999, sold: 234, rating: 4.4, reviews: 89, featured: false, hot: false, active: true, game: "Discord", image: "https://picsum.photos/seed/discord-bot/400/300", badge: null },
    { id: 56, categoryId: 7, name: "Tool Reroll Genshin Impact", description: "Phần mềm tự động reroll tài khoản Genshin Impact để kéo nhân vật 5*.", details: "• Tính năng: Auto tạo nick, auto tutorial, auto reroll\n• Mục tiêu: Ra 5★ theo ý\n• Cài đặt đơn giản\n• Video hướng dẫn kèm theo", price: 150000, originalPrice: 200000, stock: 999, sold: 178, rating: 4.3, reviews: 67, featured: false, hot: false, active: true, game: "Genshin Impact", image: "https://picsum.photos/seed/genshin-reroll/400/300", badge: null },
    { id: 57, categoryId: 7, name: "Macro Gaming - Anti AFK Pro", description: "Tool chống AFK thông minh, hỗ trợ macro phím tùy chỉnh mọi game PC.", details: "• Hỗ trợ: Mọi game PC\n• Tính năng: Anti AFK, macro phím tùy chỉnh\n• Không bị phát hiện\n• Giao ngay sau khi mua", price: 100000, originalPrice: 150000, stock: 999, sold: 456, rating: 4.5, reviews: 178, featured: false, hot: false, active: true, game: "All Games", image: "https://picsum.photos/seed/macro-pro/400/300", badge: null },
    { id: 58, categoryId: 7, name: "VPN Gaming Premium - 3 Tháng", description: "VPN chuyên cho gaming, giảm ping, bảo vệ tài khoản và unblock game.", details: "• Thời hạn: 3 tháng\n• Server: 50+ quốc gia\n• Tốc độ: Không giới hạn\n• Server gaming thấp ping\n• 5 thiết bị đồng thời", price: 180000, originalPrice: 240000, stock: 999, sold: 567, rating: 4.6, reviews: 234, featured: false, hot: false, active: true, game: "All Games", image: "https://picsum.photos/seed/vpn-gaming/400/300", badge: null },
    // ============ CATEGORY 8: Thẻ nạp / Voucher ============
    { id: 59, categoryId: 8, name: "Thẻ VCoin Garena - 500.000 VNĐ", description: "Thẻ nạp VCoin Garena mệnh giá 500,000 VNĐ dùng cho mọi game Garena.", details: "• Mệnh giá: 500,000 VNĐ\n• Loại: VCoin Garena\n• Dùng cho: LMHT, FIFA Online, v.v.\n• Giao ngay qua code\n• Không hết hạn", price: 510000, originalPrice: 520000, stock: 999, sold: 1234, rating: 4.9, reviews: 567, featured: true, hot: true, active: true, game: "Garena", image: "https://picsum.photos/seed/vcoin500/400/300", badge: "HOT" },
    { id: 60, categoryId: 8, name: "Thẻ Google Play - 200.000 VNĐ", description: "Thẻ nạp Google Play 200,000 VNĐ để mua app và game Android.", details: "• Mệnh giá: 200,000 VNĐ\n• Nền tảng: Android\n• Giao ngay qua code\n• Không hết hạn", price: 205000, originalPrice: 210000, stock: 999, sold: 890, rating: 4.8, reviews: 345, featured: false, hot: false, active: true, game: "Android", image: "https://picsum.photos/seed/gplay-200/400/300", badge: null },
    { id: 61, categoryId: 8, name: "iTunes / App Store - 200.000 VNĐ", description: "iTunes/App Store Gift Card 200,000 VNĐ cho iOS và macOS.", details: "• Mệnh giá: 200,000 VNĐ\n• Nền tảng: iOS/macOS\n• Giao ngay qua code\n• Không hết hạn", price: 210000, originalPrice: 215000, stock: 999, sold: 567, rating: 4.8, reviews: 234, featured: false, hot: false, active: true, game: "Apple iOS", image: "https://picsum.photos/seed/itunes200/400/300", badge: null },
    { id: 62, categoryId: 8, name: "Voucher Steam - 300.000 VNĐ", description: "Voucher Steam trị giá 300,000 VNĐ để mua game yêu thích.", details: "• Giá trị: 300,000 VNĐ\n• Platform: Steam\n• Giao ngay qua email\n• Không hết hạn", price: 315000, originalPrice: 320000, stock: 999, sold: 789, rating: 4.9, reviews: 345, featured: false, hot: false, active: true, game: "Steam", image: "https://picsum.photos/seed/steam-vou/400/300", badge: null },
    { id: 63, categoryId: 8, name: "Thẻ Viettel - 100.000 VNĐ", description: "Thẻ Viettel mệnh giá 100K dùng nạp vào các game liên kết Viettel.", details: "• Mệnh giá: 100,000 VNĐ\n• Mạng: Viettel\n• Giao ngay qua code\n• Hỗ trợ: LMHT, FIFA, v.v.", price: 100000, originalPrice: 103000, stock: 999, sold: 2345, rating: 4.7, reviews: 678, featured: false, hot: false, active: true, game: "Multi-game", image: "https://picsum.photos/seed/viettel100/400/300", badge: null },

    // ============ BỔ SUNG 100 SẢN PHẨM MỚI ============

    // ===== CAT 1: Tài khoản Game (thêm) =====
    { id: 64, categoryId: 1, name: "Nick Honor of Kings - Vương Giả", description: "Tài khoản Honor of Kings rank cao nhất Vương Giả, nhiều tướng và skin độc.", details: "• Server: Đông Nam Á\n• Rank: Vương Giả (Master)\n• Tướng: 80+\n• Skin 5 sao: 6 bộ\n• Bảo hành 7 ngày", price: 280000, originalPrice: 400000, stock: 6, sold: 123, rating: 4.7, reviews: 55, featured: false, hot: true, active: true, game: "Honor of Kings", image: "https://picsum.photos/seed/hok-king/400/300", badge: "HOT" },
    { id: 65, categoryId: 1, name: "Nick Liên Quân Mobile - Rank Thách Đấu", description: "Tài khoản Liên Quân Mobile rank Thách Đấu, full tướng và nhiều skin hiếm.", details: "• Server: VN\n• Rank: Thách Đấu\n• Tướng: full 100+\n• Skin Tinh Anh: 4 bộ\n• Skin Truyền Thuyết: 2 bộ\n• Bảo hành 7 ngày", price: 350000, originalPrice: 500000, stock: 5, sold: 189, rating: 4.8, reviews: 78, featured: true, hot: true, active: true, game: "Liên Quân Mobile", image: "https://picsum.photos/seed/lqm-challenger/400/300", badge: "HOT" },
    { id: 66, categoryId: 1, name: "Nick Liên Quân Mobile - Rank Vàng", description: "Tài khoản Liên Quân rank Vàng, giá rẻ phù hợp người mới chơi.", details: "• Server: VN\n• Rank: Vàng III\n• Tướng: 40+\n• Skin: 8+\n• Bảo hành 3 ngày", price: 60000, originalPrice: 90000, stock: 30, sold: 456, rating: 4.4, reviews: 167, featured: false, hot: false, active: true, game: "Liên Quân Mobile", image: "https://picsum.photos/seed/lqm-gold/400/300", badge: "SALE" },
    { id: 67, categoryId: 1, name: "Nick Apex Legends - Rank Predator", description: "Tài khoản Apex Legends đạt Predator, nhiều skin heirloom và legend skin xịn.", details: "• Platform: PC (Origin/EA)\n• Rank: Predator\n• Heirloom: 1 bộ\n• Legend Skin: 30+\n• Level: 500+\n• Bảo hành 7 ngày", price: 600000, originalPrice: 900000, stock: 3, sold: 34, rating: 4.9, reviews: 22, featured: true, hot: true, active: true, game: "Apex Legends", image: "https://picsum.photos/seed/apex-pred/400/300", badge: "VIP" },
    { id: 68, categoryId: 1, name: "Nick Apex Legends - Diamond + Skins", description: "Tài khoản Apex Legends rank Diamond, nhiều skin và 1 heirloom.", details: "• Platform: PC\n• Rank: Diamond II\n• Level: 300+\n• Legend Skin: 20+\n• Bảo hành 5 ngày", price: 250000, originalPrice: 350000, stock: 8, sold: 67, rating: 4.7, reviews: 30, featured: false, hot: false, active: true, game: "Apex Legends", image: "https://picsum.photos/seed/apex-diam/400/300", badge: null },
    { id: 69, categoryId: 1, name: "Nick Overwatch 2 - Top 500", description: "Tài khoản Overwatch 2 Top 500, nhiều skin Legendary và Golden Gun.", details: "• Platform: PC (Battle.net)\n• Rank: Top 500\n• Skin Legendary: 15+\n• Golden Gun: 3\n• SR: 4500+\n• Bảo hành 7 ngày", price: 700000, originalPrice: 1000000, stock: 2, sold: 18, rating: 5.0, reviews: 12, featured: true, hot: false, active: true, game: "Overwatch 2", image: "https://picsum.photos/seed/ow2-top500/400/300", badge: "VIP" },
    { id: 70, categoryId: 1, name: "Nick Dota 2 - Divine + Immortal Items", description: "Tài khoản Dota 2 rank Divine, nhiều item Immortal và Arcana hiếm.", details: "• Platform: Steam\n• Rank: Divine 3\n• Immortal Items: 8+\n• Arcana: 2\n• Behavior Score: 9000+\n• Bảo hành 7 ngày", price: 400000, originalPrice: 600000, stock: 4, sold: 45, rating: 4.8, reviews: 28, featured: false, hot: true, active: true, game: "Dota 2", image: "https://picsum.photos/seed/dota2-divine/400/300", badge: "HOT" },
    { id: 71, categoryId: 1, name: "Nick FIFA Online 4 - 100M Coins", description: "Tài khoản FIFA Online 4 cấp cao, đội hình 100M+ coins, squad rating 90+.", details: "• Server: Garena VN\n• Squad Rating: 90+\n• Coins: 100,000,000\n• Có nhiều player 5 sao\n• Bảo hành 5 ngày", price: 500000, originalPrice: 700000, stock: 4, sold: 89, rating: 4.7, reviews: 40, featured: true, hot: true, active: true, game: "FIFA Online 4", image: "https://picsum.photos/seed/fifa-100m/400/300", badge: "HOT" },
    { id: 72, categoryId: 1, name: "Nick FIFA Online 4 - 10M Coins Starter", description: "Tài khoản FIFA Online 4 starter, 10M coins để xây dựng đội hình.", details: "• Server: Garena VN\n• Coins: 10,000,000\n• Rating: 82+\n• Bảo hành 3 ngày", price: 80000, originalPrice: 120000, stock: 20, sold: 345, rating: 4.5, reviews: 130, featured: false, hot: false, active: true, game: "FIFA Online 4", image: "https://picsum.photos/seed/fifa-10m/400/300", badge: "SALE" },
    { id: 73, categoryId: 1, name: "Nick Brawl Stars - 50000 Trophies", description: "Tài khoản Brawl Stars 50000 Trophies, nhiều brawler và skin hiếm.", details: "• Trophies: 50,000+\n• Brawler: 60+\n• Brawler Max: 20+\n• Skin Legendary: 5\n• Gems: 1000+\n• Bảo hành 7 ngày", price: 400000, originalPrice: 600000, stock: 5, sold: 67, rating: 4.8, reviews: 32, featured: false, hot: true, active: true, game: "Brawl Stars", image: "https://picsum.photos/seed/brawl-50k/400/300", badge: "HOT" },
    { id: 74, categoryId: 1, name: "Nick Among Us - VIP Account", description: "Tài khoản Among Us với tất cả cosmetic, nhiều hat và skin độc.", details: "• Platform: PC/Mobile\n• Hat: 100+ loại\n• Skin: 50+ bộ\n• Pet: 20+\n• Bảo hành 14 ngày", price: 50000, originalPrice: 80000, stock: 50, sold: 234, rating: 4.4, reviews: 89, featured: false, hot: false, active: true, game: "Among Us", image: "https://picsum.photos/seed/among-vip/400/300", badge: null },
    { id: 75, categoryId: 1, name: "Nick Fortnite - OG Account Chapter 1", description: "Tài khoản Fortnite từ Chapter 1, có skin OG Skull Trooper và Black Knight.", details: "• Skin OG: Skull Trooper, Black Knight, Ghoul Trooper\n• V-Bucks: 2000\n• Level: 200+\n• Bảo hành 7 ngày", price: 1500000, originalPrice: 2500000, stock: 1, sold: 8, rating: 5.0, reviews: 6, featured: true, hot: true, active: true, game: "Fortnite", image: "https://picsum.photos/seed/fn-og/400/300", badge: "VIP" },
    { id: 76, categoryId: 1, name: "Nick Arena of Valor - Rank Challenger", description: "Tài khoản AoV rank Challenger VN, đầy đủ tướng và skin đẹp.", details: "• Server: VN\n• Rank: Challenger\n• Tướng: 100+\n• Skin: 30+\n• Gems: 5000\n• Bảo hành 7 ngày", price: 200000, originalPrice: 300000, stock: 8, sold: 145, rating: 4.6, reviews: 60, featured: false, hot: false, active: true, game: "Arena of Valor", image: "https://picsum.photos/seed/aov-chall/400/300", badge: null },
    { id: 77, categoryId: 1, name: "Nick Diablo IV - Season 4 Full Build", description: "Tài khoản Diablo IV Season 4, nhân vật level 100 full build end-game.", details: "• Class: Necromancer\n• Level: 100 (Paragon 300+)\n• Gear: Sacred Unique\n• Gold: 10B+\n• Season Journey: Hoàn thành\n• Bảo hành 7 ngày", price: 350000, originalPrice: 500000, stock: 4, sold: 34, rating: 4.7, reviews: 20, featured: false, hot: false, active: true, game: "Diablo IV", image: "https://picsum.photos/seed/d4-s4/400/300", badge: null },
    { id: 78, categoryId: 1, name: "Nick Pokémon GO - Level 50 Mystic", description: "Tài khoản Pokémon GO level 50 đội Mystic, nhiều Legendary và Shiny.", details: "• Level: 50\n• Team: Mystic\n• Legendary: 50+\n• Shiny: 30+\n• Pokédex: 700+\n• Candy XL: Nhiều\n• Bảo hành 7 ngày", price: 800000, originalPrice: 1200000, stock: 2, sold: 15, rating: 4.9, reviews: 10, featured: true, hot: false, active: true, game: "Pokémon GO", image: "https://picsum.photos/seed/pogo-50/400/300", badge: "VIP" },
    { id: 79, categoryId: 1, name: "Nick Hay Day - Lv 100 Full Farm", description: "Tài khoản Hay Day level 100, nông trại đã max, nhiều diamond và vật liệu.", details: "• Level: 100\n• Farm: Full nâng cấp\n• Diamond: 5000+\n• Voucher: 500+\n• Bảo hành 7 ngày", price: 300000, originalPrice: 450000, stock: 5, sold: 56, rating: 4.6, reviews: 25, featured: false, hot: false, active: true, game: "Hay Day", image: "https://picsum.photos/seed/hayday-100/400/300", badge: null },
    { id: 80, categoryId: 1, name: "Nick Call of Duty Mobile - Legendary", description: "Tài khoản CoD Mobile rank Legendary, nhiều skin súng và operator xịn.", details: "• Rank: Legendary\n• Operator Skin: 15+\n• Weapon Blueprint: 20+\n• Battle Pass: Max\n• CP dư: 1000\n• Bảo hành 7 ngày", price: 450000, originalPrice: 650000, stock: 5, sold: 78, rating: 4.7, reviews: 38, featured: false, hot: true, active: true, game: "Call of Duty Mobile", image: "https://picsum.photos/seed/codm-legend/400/300", badge: "HOT" },
    { id: 81, categoryId: 1, name: "Nick Subway Surfers - 10M Coins", description: "Tài khoản Subway Surfers 10M coins, nhiều nhân vật và hoverboard.", details: "• Coins: 10,000,000\n• Keys: 500\n• Nhân vật: 30+\n• Hoverboard: 20+\n• Bảo hành 7 ngày", price: 80000, originalPrice: 120000, stock: 20, sold: 234, rating: 4.4, reviews: 89, featured: false, hot: false, active: true, game: "Subway Surfers", image: "https://picsum.photos/seed/subway-10m/400/300", badge: null },

    // ===== CAT 2: Tiền tệ Game (thêm) =====
    { id: 82, categoryId: 2, name: "Gems Brawl Stars - 2000", description: "2000 Gems cho Brawl Stars để mở skin và brawl pass.", details: "• Số lượng: 2000 Gems\n• Nạp trực tiếp vào tài khoản\n• Thời gian: 5-10 phút\n• Cần: Supercell ID", price: 350000, originalPrice: 430000, stock: 999, sold: 456, rating: 4.8, reviews: 178, featured: false, hot: true, active: true, game: "Brawl Stars", image: "https://picsum.photos/seed/brawl-gems/400/300", badge: "HOT" },
    { id: 83, categoryId: 2, name: "Coins FIFA Online 4 - 50M", description: "50 triệu Coins FIFA Online 4 để mua player xịn và xây đội hình mạnh.", details: "• Số lượng: 50,000,000 Coins\n• Server: Garena VN\n• Giao qua Transfer Market\n• Thời gian: 30-60 phút", price: 250000, originalPrice: 350000, stock: 200, sold: 567, rating: 4.7, reviews: 234, featured: true, hot: true, active: true, game: "FIFA Online 4", image: "https://picsum.photos/seed/fifa-50mc/400/300", badge: "HOT" },
    { id: 84, categoryId: 2, name: "CP Call of Duty Mobile - 2400 CP", description: "2400 CP (CoD Points) cho CoD Mobile để mua Battle Pass và bundle.", details: "• Số lượng: 2400 CP\n• Nạp trực tiếp vào UID\n• Thời gian: 5-15 phút\n• Cần: Player ID", price: 300000, originalPrice: 380000, stock: 999, sold: 345, rating: 4.8, reviews: 145, featured: false, hot: false, active: true, game: "Call of Duty Mobile", image: "https://picsum.photos/seed/codm-cp/400/300", badge: null },
    { id: 85, categoryId: 2, name: "Honor Coins Honor of Kings - 6000", description: "6000 Honor Coins cho Honor of Kings để mua skin và tướng mới.", details: "• Số lượng: 6000 Token\n• Server: SEA\n• Thời gian: 5-10 phút\n• Cần: UID", price: 200000, originalPrice: 260000, stock: 999, sold: 234, rating: 4.7, reviews: 98, featured: false, hot: false, active: true, game: "Honor of Kings", image: "https://picsum.photos/seed/hok-coins/400/300", badge: null },
    { id: 86, categoryId: 2, name: "Tickets Liên Quân Mobile - 5000", description: "5000 Tickets Liên Quân Mobile để quay skin và mua tướng.", details: "• Số lượng: 5000 Voucher\n• Server: VN\n• Thời gian: 5-10 phút\n• Cần: In-game ID", price: 150000, originalPrice: 200000, stock: 999, sold: 678, rating: 4.8, reviews: 267, featured: false, hot: true, active: true, game: "Liên Quân Mobile", image: "https://picsum.photos/seed/lqm-tickets/400/300", badge: "HOT" },
    { id: 87, categoryId: 2, name: "Crystal Clash Royale - 10000", description: "10000 Crystal cho Clash Royale, nâng cấp thẻ bài nhanh chóng.", details: "• Số lượng: 10,000 Crystal\n• Giao qua Gift Card\n• Thời gian: 10-15 phút", price: 180000, originalPrice: 220000, stock: 999, sold: 345, rating: 4.6, reviews: 134, featured: false, hot: false, active: true, game: "Clash Royale", image: "https://picsum.photos/seed/cr-crystal/400/300", badge: null },
    { id: 88, categoryId: 2, name: "Wild Cores Wild Rift - 3250", description: "3250 Wild Cores cho Liên Minh Tốc Chiến (Wild Rift).", details: "• Số lượng: 3250 Wild Cores\n• Server: SEA/VN\n• Thời gian: 5-10 phút\n• Cần: Riot ID", price: 320000, originalPrice: 400000, stock: 999, sold: 456, rating: 4.8, reviews: 189, featured: true, hot: false, active: true, game: "Wild Rift", image: "https://picsum.photos/seed/wr-cores/400/300", badge: null },
    { id: 89, categoryId: 2, name: "Star Bits Hay Day - 10000", description: "10000 Diamond cho Hay Day, mua máy móc và trang trí nông trại.", details: "• Số lượng: 10,000 Diamonds\n• Giao qua Gift Card\n• Thời gian: 10-20 phút", price: 250000, originalPrice: 320000, stock: 999, sold: 123, rating: 4.5, reviews: 56, featured: false, hot: false, active: true, game: "Hay Day", image: "https://picsum.photos/seed/hayday-dm/400/300", badge: null },
    { id: 90, categoryId: 2, name: "Pokecoins Pokémon GO - 14500", description: "14500 PokéCoins cho Pokémon GO, mua Raid Pass và storage.", details: "• Số lượng: 14,500 PokéCoins\n• Giao qua Google/Apple Gift Card\n• Thời gian: 10-20 phút", price: 400000, originalPrice: 500000, stock: 999, sold: 234, rating: 4.7, reviews: 98, featured: false, hot: false, active: true, game: "Pokémon GO", image: "https://picsum.photos/seed/pogo-coins/400/300", badge: null },
    { id: 91, categoryId: 2, name: "Lingots Duolingo - 1 Năm Plus", description: "Đăng ký Duolingo Plus 1 năm, học ngôn ngữ không quảng cáo + offline.", details: "• Gói: Duolingo Plus/Super\n• Thời hạn: 1 năm\n• Không quảng cáo\n• Học offline\n• Giao ngay qua link", price: 200000, originalPrice: 300000, stock: 999, sold: 345, rating: 4.8, reviews: 145, featured: false, hot: false, active: true, game: "Duolingo", image: "https://picsum.photos/seed/duo-plus/400/300", badge: "SALE" },
    { id: 92, categoryId: 2, name: "Bang Bang Mobilé Legends - 5000 Diamond", description: "5000 Diamond cho Mobile Legends Bang Bang để mua skin mới nhất.", details: "• Số lượng: 5000 Diamond\n• Server: SEA\n• Nạp trực tiếp vào ID\n• Thời gian: 5-15 phút", price: 500000, originalPrice: 620000, stock: 999, sold: 890, rating: 4.9, reviews: 345, featured: true, hot: true, active: true, game: "Mobile Legends", image: "https://picsum.photos/seed/mlbb-5kdm/400/300", badge: "HOT" },
    { id: 93, categoryId: 2, name: "Coupons Stumble Guys - 2000", description: "2000 Gems cho Stumble Guys, mở khóa emote và skin nhân vật.", details: "• Số lượng: 2000 Gems\n• Giao qua Gift Card\n• Thời gian: 5-10 phút", price: 120000, originalPrice: 160000, stock: 999, sold: 234, rating: 4.5, reviews: 89, featured: false, hot: false, active: true, game: "Stumble Guys", image: "https://picsum.photos/seed/stumble-gems/400/300", badge: null },

    // ===== CAT 3: Vật phẩm / Item (thêm) =====
    { id: 94, categoryId: 3, name: "Skin Wild Rift - Elementalist Lux", description: "Skin Elementalist Lux siêu đẹp trong Liên Minh Tốc Chiến.", details: "• Nhân vật: Lux\n• Skin: Elementalist (Ultimate)\n• Bao gồm: 10 dạng biến đổi\n• Giao qua account", price: 300000, originalPrice: 450000, stock: 8, sold: 67, rating: 4.9, reviews: 30, featured: false, hot: true, active: true, game: "Wild Rift", image: "https://picsum.photos/seed/wr-lux/400/300", badge: "HOT" },
    { id: 95, categoryId: 3, name: "Heirloom Apex Legends - Kunai", description: "Wraith Kunai Heirloom cực hiếm trong Apex Legends.", details: "• Nhân vật: Wraith\n• Item: Kunai Heirloom\n• Giao qua account\n• Bảo hành 7 ngày", price: 500000, originalPrice: 700000, stock: 3, sold: 25, rating: 5.0, reviews: 18, featured: true, hot: false, active: true, game: "Apex Legends", image: "https://picsum.photos/seed/apex-kunai/400/300", badge: "HIẾM" },
    { id: 96, categoryId: 3, name: "Bundle CoD Mobile - Legendary Operator", description: "Bundle Operator Legendary trong Call of Duty Mobile, full set cực chất.", details: "• Loại: Legendary Bundle\n• Bao gồm: Operator Skin + 5 Blueprints + Calling Card\n• Giao qua account", price: 350000, originalPrice: 500000, stock: 6, sold: 45, rating: 4.7, reviews: 22, featured: false, hot: false, active: true, game: "Call of Duty Mobile", image: "https://picsum.photos/seed/codm-bundle/400/300", badge: null },
    { id: 97, categoryId: 3, name: "Set Trang Phục Liên Quân - Tier 1", description: "Bộ trang phục Tier 1 đầy đủ cho tướng yêu thích trong Liên Quân Mobile.", details: "• Tier: 1 (cao nhất)\n• Bao gồm: Skin + Effect + Voice + Recall\n• Tướng: Theo yêu cầu\n• Giao qua account", price: 250000, originalPrice: 380000, stock: 10, sold: 89, rating: 4.8, reviews: 40, featured: false, hot: false, active: true, game: "Liên Quân Mobile", image: "https://picsum.photos/seed/lqm-t1/400/300", badge: null },
    { id: 98, categoryId: 3, name: "Arcana Set Dota 2 - Full 3 Arcana", description: "3 skin Arcana cực hiếm cho Dota 2, bao gồm Terrorblade, Juggernaut và PA.", details: "• Arcana 1: Juggernaut Arcana\n• Arcana 2: Terrorblade Arcana\n• Arcana 3: Phantom Assassin Arcana\n• Giao qua account\n• Bảo hành 7 ngày", price: 600000, originalPrice: 900000, stock: 3, sold: 15, rating: 5.0, reviews: 10, featured: true, hot: false, active: true, game: "Dota 2", image: "https://picsum.photos/seed/dota2-arcana/400/300", badge: "HIẾM" },
    { id: 99, categoryId: 3, name: "Mega Knight Skin Clash Royale", description: "Skin Mega Knight siêu đẹp cho Clash Royale, hiệu ứng lung linh.", details: "• Thẻ: Mega Knight\n• Skin: Legendary\n• Giao qua Clan Trading\n• Server: Global", price: 80000, originalPrice: 120000, stock: 15, sold: 123, rating: 4.6, reviews: 50, featured: false, hot: false, active: true, game: "Clash Royale", image: "https://picsum.photos/seed/cr-mk/400/300", badge: null },
    { id: 100, categoryId: 3, name: "Pet Neon Fly Ride - Adopt Me Roblox", description: "Pet Neon Fly Ride cực hiếm trong Adopt Me, tất cả pet đều đã neon và fly/ride.", details: "• Game: Adopt Me (Roblox)\n• Pet: Neon + Fly + Ride\n• Loại: Legendary Pet\n• Giao qua Trade in-game", price: 300000, originalPrice: 450000, stock: 4, sold: 34, rating: 4.9, reviews: 20, featured: false, hot: true, active: true, game: "Roblox - Adopt Me", image: "https://picsum.photos/seed/roblox-neon/400/300", badge: "HOT" },
    { id: 101, categoryId: 3, name: "Skin Honor of Kings - S Tier Full Effect", description: "Skin S-Tier đẹp nhất trong Honor of Kings, full hiệu ứng và animation.", details: "• Hệ: S-Tier\n• Bao gồm: Skin + Effect + Recall + Voice\n• Giao qua account", price: 200000, originalPrice: 300000, stock: 8, sold: 56, rating: 4.7, reviews: 25, featured: false, hot: false, active: true, game: "Honor of Kings", image: "https://picsum.photos/seed/hok-stier/400/300", badge: null },
    { id: 102, categoryId: 3, name: "Item Immortal Dota 2 - 10 Pieces", description: "10 item Immortal hiếm trong Dota 2, trị giá cao trên Steam Market.", details: "• Số lượng: 10 Immortal Items\n• Giá trị mỗi item: $5-20\n• Giao qua Steam Trade\n• Bảo hành: Giao thành công", price: 500000, originalPrice: 700000, stock: 5, sold: 23, rating: 4.8, reviews: 15, featured: false, hot: false, active: true, game: "Dota 2", image: "https://picsum.photos/seed/dota2-imm10/400/300", badge: "HIẾM" },
    { id: 103, categoryId: 3, name: "Skin Subway Surfers - All Characters", description: "Tài khoản Subway Surfers với tất cả nhân vật và board được mở khóa.", details: "• Nhân vật: 60+ (tất cả)\n• Hoverboard: 80+\n• Super Mystery Box: Nhiều\n• Bảo hành 7 ngày", price: 150000, originalPrice: 220000, stock: 10, sold: 89, rating: 4.5, reviews: 40, featured: false, hot: false, active: true, game: "Subway Surfers", image: "https://picsum.photos/seed/subway-all/400/300", badge: null },

    // ===== CAT 4: Key & Code (thêm) =====
    { id: 104, categoryId: 4, name: "Key Adobe Photoshop CC - 1 Năm", description: "Bản quyền Adobe Photoshop CC 1 năm cho 1 thiết bị, đầy đủ tính năng.", details: "• Phần mềm: Adobe Photoshop CC\n• Thời hạn: 1 năm\n• Thiết bị: 1 máy\n• Bao gồm: 100GB Cloud Storage\n• Giao ngay qua email", price: 350000, originalPrice: 500000, stock: 999, sold: 345, rating: 4.8, reviews: 156, featured: false, hot: false, active: true, game: "Adobe", image: "https://picsum.photos/seed/adobe-ps/400/300", badge: "SALE" },
    { id: 105, categoryId: 4, name: "Key Spotify Premium - 3 Tháng", description: "Tài khoản Spotify Premium 3 tháng, nghe nhạc không quảng cáo offline.", details: "• Gói: Spotify Premium Individual\n• Thời hạn: 3 tháng\n• Nghe offline + không quảng cáo\n• Giao ngay qua email", price: 120000, originalPrice: 180000, stock: 999, sold: 1234, rating: 4.7, reviews: 456, featured: true, hot: true, active: true, game: "Spotify", image: "https://picsum.photos/seed/spotify3m/400/300", badge: "HOT" },
    { id: 106, categoryId: 4, name: "Key Disney+ - 1 Năm", description: "Tài khoản Disney+ 1 năm, xem phim Marvel, Star Wars, Pixar 4K.", details: "• Gói: Disney+ Standard\n• Thời hạn: 1 năm\n• Chất lượng: 4K UHD\n• Giao ngay qua email", price: 180000, originalPrice: 260000, stock: 999, sold: 567, rating: 4.7, reviews: 234, featured: false, hot: false, active: true, game: "Disney+", image: "https://picsum.photos/seed/disney-plus/400/300", badge: null },
    { id: 107, categoryId: 4, name: "Key HBO Max - 1 Tháng", description: "Tài khoản HBO Max 1 tháng, xem series Game of Thrones, Euphoria...", details: "• Gói: HBO Max Ad-Lite\n• Thời hạn: 1 tháng\n• Nội dung: HBO Originals, DC, Max Originals\n• Giao ngay qua email", price: 80000, originalPrice: 110000, stock: 999, sold: 345, rating: 4.6, reviews: 134, featured: false, hot: false, active: true, game: "HBO Max", image: "https://picsum.photos/seed/hbomax/400/300", badge: null },
    { id: 108, categoryId: 4, name: "Key Canva Pro - 1 Năm", description: "Canva Pro 1 năm, thiết kế chuyên nghiệp với 100M+ template và asset.", details: "• Gói: Canva Pro\n• Thời hạn: 1 năm\n• Template: 100M+\n• Brandkit: Có\n• Xóa nền AI: Không giới hạn\n• Giao ngay qua email", price: 250000, originalPrice: 380000, stock: 999, sold: 789, rating: 4.8, reviews: 345, featured: true, hot: true, active: true, game: "Canva", image: "https://picsum.photos/seed/canva-pro/400/300", badge: "HOT" },
    { id: 109, categoryId: 4, name: "Key EA Play Pro - 1 Năm PC", description: "EA Play Pro 1 năm cho PC, chơi không giới hạn tất cả game EA.", details: "• Gói: EA Play Pro\n• Thời hạn: 1 năm\n• Game: FIFA, Battlefield, Apex, Sims, Need for Speed...\n• Platform: PC (EA App)\n• Giao ngay qua email", price: 400000, originalPrice: 600000, stock: 999, sold: 234, rating: 4.7, reviews: 98, featured: false, hot: false, active: true, game: "EA Play", image: "https://picsum.photos/seed/ea-play-pro/400/300", badge: null },
    { id: 110, categoryId: 4, name: "Key Ubisoft+ - 1 Tháng", description: "Ubisoft+ 1 tháng, chơi Assassin's Creed, Far Cry, Rainbow Six Siege...", details: "• Gói: Ubisoft+\n• Thời hạn: 1 tháng\n• Game: 100+ tựa game Ubisoft\n• Giao ngay qua email", price: 180000, originalPrice: 250000, stock: 999, sold: 156, rating: 4.5, reviews: 67, featured: false, hot: false, active: true, game: "Ubisoft", image: "https://picsum.photos/seed/ubisoft-plus/400/300", badge: null },
    { id: 111, categoryId: 4, name: "Key Norton 360 Deluxe - 1 Năm 3PC", description: "Norton 360 Deluxe bảo vệ 3 thiết bị 1 năm, kèm VPN và Dark Web Monitor.", details: "• Phần mềm: Norton 360 Deluxe\n• Thời hạn: 1 năm\n• Thiết bị: 3 PC/Mac/Mobile\n• Bao gồm: VPN + Dark Web Monitor + 50GB Backup\n• Giao ngay qua email", price: 200000, originalPrice: 300000, stock: 999, sold: 345, rating: 4.7, reviews: 145, featured: false, hot: false, active: true, game: "Norton", image: "https://picsum.photos/seed/norton360/400/300", badge: null },
    { id: 112, categoryId: 4, name: "Key Grammarly Premium - 1 Năm", description: "Grammarly Premium 1 năm, kiểm tra và cải thiện văn bản tiếng Anh AI.", details: "• Gói: Grammarly Premium\n• Thời hạn: 1 năm\n• Tính năng: AI Writing Assistant, Plagiarism Check\n• Giao ngay qua email", price: 200000, originalPrice: 300000, stock: 999, sold: 456, rating: 4.8, reviews: 189, featured: false, hot: false, active: true, game: "Grammarly", image: "https://picsum.photos/seed/grammarly/400/300", badge: "SALE" },
    { id: 113, categoryId: 4, name: "Key ChatGPT Plus - 1 Tháng", description: "ChatGPT Plus 1 tháng, dùng GPT-4o không giới hạn + DALL-E 3.", details: "• Gói: ChatGPT Plus\n• Thời hạn: 1 tháng\n• GPT-4o: Không giới hạn\n• DALL-E 3, GPTs, Web Browse\n• Giao ngay qua email", price: 350000, originalPrice: 500000, stock: 999, sold: 1234, rating: 4.9, reviews: 567, featured: true, hot: true, active: true, game: "OpenAI", image: "https://picsum.photos/seed/chatgpt-plus/400/300", badge: "HOT" },
    { id: 114, categoryId: 4, name: "Key PlayStation Plus Essential - 3 Tháng", description: "PS Plus Essential 3 tháng, chơi online và nhận game miễn phí hàng tháng.", details: "• Gói: PS Plus Essential\n• Thời hạn: 3 tháng\n• Chơi online PS4/PS5\n• Free Game hàng tháng\n• Giao ngay qua code", price: 300000, originalPrice: 380000, stock: 999, sold: 345, rating: 4.7, reviews: 145, featured: false, hot: false, active: true, game: "PlayStation", image: "https://picsum.photos/seed/psplus3m/400/300", badge: null },
    { id: 115, categoryId: 4, name: "Key Nintendo Switch Online - 1 Năm", description: "Nintendo Switch Online 1 năm, chơi Pokémon, Mario Kart online.", details: "• Gói: Nintendo Switch Online Individual\n• Thời hạn: 1 năm\n• Chơi online + NES/SNES library\n• Giao ngay qua code", price: 250000, originalPrice: 320000, stock: 999, sold: 234, rating: 4.6, reviews: 98, featured: false, hot: false, active: true, game: "Nintendo Switch", image: "https://picsum.photos/seed/nso-1y/400/300", badge: null },
    { id: 116, categoryId: 4, name: "Key Prime Gaming - Amazon 1 Năm", description: "Amazon Prime Gaming 1 năm, nhận game miễn phí hàng tháng + Twitch Prime.", details: "• Gói: Amazon Prime (Gaming included)\n• Thời hạn: 1 năm\n• Free Games mỗi tháng\n• In-game loot cho 20+ game\n• Giao ngay qua email", price: 300000, originalPrice: 420000, stock: 999, sold: 189, rating: 4.6, reviews: 78, featured: false, hot: false, active: true, game: "Amazon Gaming", image: "https://picsum.photos/seed/prime-gaming/400/300", badge: null },

    // ===== CAT 5: Nick Clone / Buff (thêm) =====
    { id: 117, categoryId: 5, name: "Nick Facebook Via - Cổ 2 Năm", description: "Nick Facebook cổ 2 năm tuổi, trắng sạch, dùng được quảng cáo.", details: "• Tuổi: 2 năm+\n• Xác minh: SĐT\n• Trạng thái: Sạch\n• Có thể chạy quảng cáo\n• Kèm cookies\n• Bảo hành 3 ngày", price: 80000, originalPrice: 120000, stock: 80, sold: 567, rating: 4.5, reviews: 234, featured: false, hot: true, active: true, game: "Facebook", image: "https://picsum.photos/seed/fb-via/400/300", badge: "HOT" },
    { id: 118, categoryId: 5, name: "Nick Facebook BM2 - Tạo Được BM", description: "Facebook clone đã tạo Business Manager 2, dùng chạy quảng cáo ngay.", details: "• Loại: BM2 (Business Manager 2)\n• Ads Account: Tạo được\n• Xác minh: SĐT\n• Kèm cookies + user agent\n• Bảo hành 3 ngày", price: 120000, originalPrice: 180000, stock: 50, sold: 789, rating: 4.6, reviews: 312, featured: true, hot: true, active: true, game: "Facebook Ads", image: "https://picsum.photos/seed/fb-bm2/400/300", badge: "HOT" },
    { id: 119, categoryId: 5, name: "Gmail PVA - 5 Tài Khoản Bulk", description: "5 tài khoản Gmail đã xác minh SĐT, phù hợp tạo tài khoản game và dịch vụ.", details: "• Số lượng: 5 tài khoản Gmail\n• Xác minh: SĐT thật\n• Tuổi: 1-3 tháng\n• Recovery: Có\n• Bảo hành 3 ngày", price: 120000, originalPrice: 180000, stock: 100, sold: 1234, rating: 4.5, reviews: 456, featured: false, hot: true, active: true, game: "Gmail/Google", image: "https://picsum.photos/seed/gmail-5pva/400/300", badge: "HOT" },
    { id: 120, categoryId: 5, name: "TikTok Account - 5000 Followers Niche", description: "Tài khoản TikTok 5000 followers theo niche cụ thể, engagement tốt.", details: "• Followers: 5000+ (thật)\n• Niche: Gaming/Lifestyle/Food\n• Engagement rate: 6%+\n• Video: 50+\n• Bảo hành 7 ngày", price: 250000, originalPrice: 380000, stock: 20, sold: 145, rating: 4.6, reviews: 60, featured: false, hot: false, active: true, game: "TikTok", image: "https://picsum.photos/seed/tiktok-5k/400/300", badge: null },
    { id: 121, categoryId: 5, name: "Instagram Account - 10K Followers", description: "Tài khoản Instagram 10K followers thật, monetize được, tag location.", details: "• Followers: 10,000+ thật\n• Niche: Beauty/Gaming/Travel\n• Engagement: 4%+\n• 10K Swipe-up link\n• Bảo hành 14 ngày", price: 500000, originalPrice: 800000, stock: 10, sold: 89, rating: 4.7, reviews: 40, featured: true, hot: true, active: true, game: "Instagram", image: "https://picsum.photos/seed/ig-10k/400/300", badge: "HOT" },
    { id: 122, categoryId: 5, name: "Shopee Seller Account - 100 Sao", description: "Tài khoản Shopee seller 100 sao, uy tín cao dùng bán hàng luôn.", details: "• Sao: 100+\n• Đánh giá: 4.8+\n• Đơn đã bán: 500+\n• Xác minh: CCCD\n• Bảo hành 7 ngày", price: 300000, originalPrice: 500000, stock: 15, sold: 89, rating: 4.7, reviews: 38, featured: false, hot: false, active: true, game: "Shopee", image: "https://picsum.photos/seed/shopee-100/400/300", badge: null },
    { id: 123, categoryId: 5, name: "Lazada Seller Account - Verified", description: "Tài khoản Lazada đã xác minh, lịch sử bán hàng tốt.", details: "• Xác minh: CCCD + SĐT\n• Đánh giá: 4.5+\n• Đơn đã bán: 200+\n• Shop: Ready to use\n• Bảo hành 7 ngày", price: 250000, originalPrice: 380000, stock: 10, sold: 56, rating: 4.5, reviews: 25, featured: false, hot: false, active: true, game: "Lazada", image: "https://picsum.photos/seed/lazada-seller/400/300", badge: null },
    { id: 124, categoryId: 5, name: "Telegram Account - Member 5000 Group", description: "Tài khoản Telegram đã tham gia nhiều group lớn, dùng marketing.", details: "• Member: 5000+ group\n• Channel join: 200+\n• Xác minh SĐT\n• Tuổi: 1 năm+\n• Bảo hành 3 ngày", price: 70000, originalPrice: 100000, stock: 60, sold: 234, rating: 4.4, reviews: 89, featured: false, hot: false, active: true, game: "Telegram", image: "https://picsum.photos/seed/tg-member/400/300", badge: null },
    { id: 125, categoryId: 5, name: "Reddit Account - Karma 10K+", description: "Tài khoản Reddit karma cao 10K+, post được vào subreddit chọn lọc.", details: "• Post Karma: 8000+\n• Comment Karma: 2000+\n• Tuổi: 2 năm+\n• Có Gold/Premium\n• Bảo hành 7 ngày", price: 150000, originalPrice: 220000, stock: 20, sold: 78, rating: 4.5, reviews: 34, featured: false, hot: false, active: true, game: "Reddit", image: "https://picsum.photos/seed/reddit-10k/400/300", badge: null },
    { id: 126, categoryId: 5, name: "LinkedIn Account - 500+ Connections", description: "Tài khoản LinkedIn với 500+ kết nối, hồ sơ chuyên nghiệp đầy đủ.", details: "• Connections: 500+\n• Profile: All-Star\n• Kinh nghiệm: Điền sẵn\n• Xác minh email\n• Bảo hành 7 ngày", price: 200000, originalPrice: 300000, stock: 15, sold: 45, rating: 4.6, reviews: 22, featured: false, hot: false, active: true, game: "LinkedIn", image: "https://picsum.photos/seed/linkedin-500/400/300", badge: null },

    // ===== CAT 6: Dịch vụ Boost (thêm) =====
    { id: 127, categoryId: 6, name: "Boost Liên Quân - Leo Rank Thách Đấu", description: "Dịch vụ leo rank Liên Quân Mobile lên Thách Đấu, an toàn và nhanh.", details: "• Từ: Huyền Thoại I trở lên\n• Đến: Thách Đấu\n• Thời gian: 7-10 ngày\n• Win rate: 70%+\n• Bảo mật 100%", price: 400000, originalPrice: 600000, stock: 10, sold: 167, rating: 4.7, reviews: 72, featured: false, hot: true, active: true, game: "Liên Quân Mobile", image: "https://picsum.photos/seed/lqm-boost/400/300", badge: "HOT" },
    { id: 128, categoryId: 6, name: "Boost Wild Rift - Master+", description: "Dịch vụ leo rank Wild Rift lên Master, cam kết chất lượng.", details: "• Từ: Diamond I\n• Đến: Master\n• Thời gian: 3-5 ngày\n• Win rate: 70%+\n• VPN bảo vệ", price: 350000, originalPrice: 500000, stock: 8, sold: 89, rating: 4.7, reviews: 42, featured: false, hot: false, active: true, game: "Wild Rift", image: "https://picsum.photos/seed/wr-boost/400/300", badge: null },
    { id: 129, categoryId: 6, name: "Boost FIFA Online 4 - Division 1", description: "Leo hạng Division 1 trong FIFA Online 4, chơi duo với pro player.", details: "• Từ: Division 5\n• Đến: Division 1\n• Phương thức: Duo boost\n• Thời gian: 3-5 ngày\n• Win rate: 65%+", price: 300000, originalPrice: 450000, stock: 12, sold: 123, rating: 4.6, reviews: 55, featured: false, hot: false, active: true, game: "FIFA Online 4", image: "https://picsum.photos/seed/fifa-boost/400/300", badge: null },
    { id: 130, categoryId: 6, name: "Cày Thuê Genshin Impact - AR 60", description: "Dịch vụ cày AR lên 60 trong Genshin Impact, hoàn thành quests và daily.", details: "• Từ: AR 55\n• Đến: AR 60\n• Bao gồm: Daily quests, World Exploration\n• Thời gian: 7-14 ngày\n• Bảo mật 100%", price: 400000, originalPrice: 600000, stock: 8, sold: 45, rating: 4.8, reviews: 25, featured: false, hot: false, active: true, game: "Genshin Impact", image: "https://picsum.photos/seed/genshin-boost/400/300", badge: null },
    { id: 131, categoryId: 6, name: "Boost Overwatch 2 - Diamond → Master", description: "Leo rank Overwatch 2 từ Diamond lên Master với booster chuyên nghiệp.", details: "• Từ: Diamond\n• Đến: Master\n• Thời gian: 3-5 ngày\n• Phương thức: Piloted\n• Cam kết hoàn tiền nếu thất bại", price: 450000, originalPrice: 650000, stock: 6, sold: 34, rating: 4.8, reviews: 20, featured: false, hot: false, active: true, game: "Overwatch 2", image: "https://picsum.photos/seed/ow2-boost/400/300", badge: null },
    { id: 132, categoryId: 6, name: "Cày Clash of Clans - TH Upgrade", description: "Dịch vụ cày tài nguyên và nâng cấp Town Hall nhanh trong CoC.", details: "• Dịch vụ: Farm vàng + Elixir + Dark Elixir\n• TH: 11→12 hoặc 12→13\n• Thời gian: 30 ngày\n• Báo cáo hàng ngày", price: 500000, originalPrice: 700000, stock: 5, sold: 23, rating: 4.7, reviews: 15, featured: false, hot: false, active: true, game: "Clash of Clans", image: "https://picsum.photos/seed/coc-boost/400/300", badge: null },
    { id: 133, categoryId: 6, name: "Boost Honor of Kings - Rank Cao", description: "Dịch vụ boost rank Honor of Kings từ Kim → Bạch Kim → Kim Cương.", details: "• Từ: Kim Cương\n• Đến: Cao Thủ\n• Thời gian: 5-7 ngày\n• Win rate: 65%+\n• Bảo mật tài khoản", price: 280000, originalPrice: 420000, stock: 10, sold: 89, rating: 4.6, reviews: 40, featured: false, hot: false, active: true, game: "Honor of Kings", image: "https://picsum.photos/seed/hok-boost/400/300", badge: null },
    { id: 134, categoryId: 6, name: "Boost Dota 2 - Ancient → Divine", description: "Leo rank Dota 2 từ Ancient lên Divine với booster 7000 MMR.", details: "• Từ: Ancient 3\n• Đến: Divine 1\n• Thời gian: 7-10 ngày\n• MMR Booster: 7000+\n• Báo cáo tiến độ", price: 600000, originalPrice: 900000, stock: 4, sold: 18, rating: 4.9, reviews: 12, featured: false, hot: false, active: true, game: "Dota 2", image: "https://picsum.photos/seed/dota2-boost/400/300", badge: null },
    { id: 135, categoryId: 6, name: "Boost Brawl Stars - 30000 Trophies", description: "Đẩy trophy Brawl Stars lên 30000, dùng brawler mạnh nhất.", details: "• Từ: 10000 trophies\n• Đến: 30000 trophies\n• Thời gian: 10-14 ngày\n• Brawler: Sử dụng tài khoản của bạn", price: 350000, originalPrice: 500000, stock: 8, sold: 45, rating: 4.7, reviews: 22, featured: false, hot: false, active: true, game: "Brawl Stars", image: "https://picsum.photos/seed/brawl-boost/400/300", badge: null },

    // ===== CAT 7: Tool & Phần mềm (thêm) =====
    { id: 136, categoryId: 7, name: "Tool Tạo Nick Game Auto - Multi Platform", description: "Phần mềm tự động tạo tài khoản game hàng loạt, hỗ trợ 20+ nền tảng.", details: "• Hỗ trợ: Garena, Riot, Supercell, Epic...\n• Tính năng: Auto register, auto verify\n• Anti-detect: Có\n• Proxy Support: Có\n• Cập nhật miễn phí", price: 400000, originalPrice: 600000, stock: 999, sold: 234, rating: 4.5, reviews: 89, featured: false, hot: false, active: true, game: "Multi Platform", image: "https://picsum.photos/seed/tool-reg/400/300", badge: null },
    { id: 137, categoryId: 7, name: "Tool Check Nick Live/Die Bulk", description: "Phần mềm kiểm tra tài khoản game còn sống hay chết hàng loạt nhanh.", details: "• Tốc độ: 1000 acc/phút\n• Hỗ trợ: 15+ game platform\n• Output: Live/Die/2FA\n• Proxy: Built-in\n• Giao ngay sau mua", price: 200000, originalPrice: 300000, stock: 999, sold: 456, rating: 4.4, reviews: 178, featured: false, hot: true, active: true, game: "Multi Game", image: "https://picsum.photos/seed/tool-check/400/300", badge: "HOT" },
    { id: 138, categoryId: 7, name: "Proxy Residential - 10GB Traffic", description: "Proxy Residential 10GB, IP thật từ 150+ quốc gia, tốc độ cao.", details: "• Loại: Residential Proxy\n• Bandwidth: 10GB\n• Quốc gia: 150+\n• Tốc độ: Cao\n• Rotating: Có\n• Thời hạn: Đến hết băng thông", price: 300000, originalPrice: 450000, stock: 999, sold: 345, rating: 4.6, reviews: 134, featured: false, hot: false, active: true, game: "Proxy", image: "https://picsum.photos/seed/proxy-10gb/400/300", badge: null },
    { id: 139, categoryId: 7, name: "Tool Spam Facebook Message Auto", description: "Phần mềm tự động gửi tin nhắn Facebook theo danh sách UID/Phone.", details: "• Tính năng: Auto message, auto friend\n• Hỗ trợ: Multi account\n• Anti-ban: Delay thông minh\n• Dashboard quản lý\n• Bản quyền: 1 thiết bị", price: 500000, originalPrice: 750000, stock: 999, sold: 178, rating: 4.3, reviews: 67, featured: false, hot: false, active: true, game: "Facebook Tool", image: "https://picsum.photos/seed/fb-spamtool/400/300", badge: null },
    { id: 140, categoryId: 7, name: "Tool Đăng Bài TikTok Hàng Loạt", description: "Phần mềm tự động đăng video TikTok nhiều tài khoản cùng lúc.", details: "• Multi Account: 50 tài khoản\n• Auto Post: Video + Caption + Hashtag\n• Schedule: Hẹn giờ đăng\n• Analytics: Theo dõi view\n• Cập nhật định kỳ", price: 600000, originalPrice: 900000, stock: 999, sold: 123, rating: 4.4, reviews: 56, featured: false, hot: false, active: true, game: "TikTok Tool", image: "https://picsum.photos/seed/tiktok-tool/400/300", badge: null },
    { id: 141, categoryId: 7, name: "Anti-Detect Browser - 3 Tháng", description: "Trình duyệt chống phát hiện tài khoản ảo, quản lý nhiều profile độc lập.", details: "• Gói: 3 tháng\n• Profile: 100 profile\n• Fingerprint: Giả lập mỗi profile\n• Proxy: Hỗ trợ mọi loại\n• Teamwork: Có", price: 350000, originalPrice: 500000, stock: 999, sold: 234, rating: 4.6, reviews: 98, featured: false, hot: true, active: true, game: "Anti-Detect", image: "https://picsum.photos/seed/antidetect/400/300", badge: "HOT" },
    { id: 142, categoryId: 7, name: "OTP Service - SĐT Ảo 100 Số", description: "Dịch vụ nhận OTP qua số điện thoại ảo, hỗ trợ 200+ dịch vụ.", details: "• Số lượng: 100 lần nhận OTP\n• Hỗ trợ: 200+ dịch vụ (Facebook, Google, Telegram...)\n• Nước: VN, US, UK, IN\n• Thời hạn: 30 ngày", price: 150000, originalPrice: 220000, stock: 999, sold: 567, rating: 4.5, reviews: 234, featured: false, hot: false, active: true, game: "OTP Service", image: "https://picsum.photos/seed/otp-100/400/300", badge: null },
    { id: 143, categoryId: 7, name: "IDM Internet Download Manager - Vĩnh Viễn", description: "Bản quyền IDM vĩnh viễn, tăng tốc download lên 5x, hỗ trợ resume.", details: "• Phần mềm: IDM 6.x\n• Bản quyền: Vĩnh viễn\n• Thiết bị: 1 PC\n• Hỗ trợ: Update miễn phí\n• Giao ngay qua email", price: 100000, originalPrice: 150000, stock: 999, sold: 789, rating: 4.7, reviews: 312, featured: false, hot: false, active: true, game: "IDM", image: "https://picsum.photos/seed/idm-life/400/300", badge: "SALE" },
    { id: 144, categoryId: 7, name: "WinRAR License - Vĩnh Viễn", description: "License WinRAR vĩnh viễn cho 1 máy tính, không còn popup nhắc nhở.", details: "• Phần mềm: WinRAR\n• Bản quyền: Vĩnh viễn\n• Thiết bị: 1 PC\n• Giao ngay qua key", price: 50000, originalPrice: 80000, stock: 999, sold: 1234, rating: 4.6, reviews: 456, featured: false, hot: false, active: true, game: "WinRAR", image: "https://picsum.photos/seed/winrar-key/400/300", badge: "SALE" },
    { id: 145, categoryId: 7, name: "CleanMyMac X - 1 Năm", description: "CleanMyMac X 1 năm, dọn rác Mac, xóa malware và tối ưu hiệu năng.", details: "• Phần mềm: CleanMyMac X\n• Thời hạn: 1 năm\n• Thiết bị: 1 Mac\n• Giao ngay qua email", price: 250000, originalPrice: 380000, stock: 999, sold: 234, rating: 4.7, reviews: 98, featured: false, hot: false, active: true, game: "CleanMyMac", image: "https://picsum.photos/seed/cleanmymac/400/300", badge: null },

    // ===== CAT 8: Thẻ nạp / Voucher (thêm) =====
    { id: 146, categoryId: 8, name: "Thẻ Mobi - 200.000 VNĐ", description: "Thẻ nạp Mobifone 200K để nạp game và dịch vụ liên kết Mobi.", details: "• Mệnh giá: 200,000 VNĐ\n• Mạng: Mobifone\n• Giao ngay qua code\n• Không hết hạn", price: 200000, originalPrice: 207000, stock: 999, sold: 1234, rating: 4.8, reviews: 456, featured: false, hot: false, active: true, game: "Multi-game", image: "https://picsum.photos/seed/mobi200/400/300", badge: null },
    { id: 147, categoryId: 8, name: "Thẻ Vina - 200.000 VNĐ", description: "Thẻ Vinaphone 200K, dùng nạp game và dịch vụ Vinaphone.", details: "• Mệnh giá: 200,000 VNĐ\n• Mạng: Vinaphone\n• Giao ngay qua code\n• Không hết hạn", price: 200000, originalPrice: 207000, stock: 999, sold: 890, rating: 4.8, reviews: 345, featured: false, hot: false, active: true, game: "Multi-game", image: "https://picsum.photos/seed/vina200/400/300", badge: null },
    { id: 148, categoryId: 8, name: "Thẻ VCoin Garena - 100.000 VNĐ", description: "Thẻ VCoin Garena 100K dùng cho tất cả game Garena tại Việt Nam.", details: "• Mệnh giá: 100,000 VNĐ\n• Dùng cho: LMHT, FIFA Online 4, CF...\n• Giao ngay qua code\n• Không hết hạn", price: 102000, originalPrice: 105000, stock: 999, sold: 2345, rating: 4.9, reviews: 789, featured: false, hot: false, active: true, game: "Garena", image: "https://picsum.photos/seed/vcoin100/400/300", badge: null },
    { id: 149, categoryId: 8, name: "Thẻ VCoin Garena - 200.000 VNĐ", description: "Thẻ VCoin Garena 200K giá tốt hơn mua lẻ, dùng tất cả game Garena.", details: "• Mệnh giá: 200,000 VNĐ\n• Dùng cho: Tất cả game Garena\n• Giao ngay qua code\n• Không hết hạn", price: 204000, originalPrice: 210000, stock: 999, sold: 1890, rating: 4.9, reviews: 678, featured: true, hot: true, active: true, game: "Garena", image: "https://picsum.photos/seed/vcoin200/400/300", badge: "HOT" },
    { id: 150, categoryId: 8, name: "Gift Card Amazon - $10 USD", description: "Amazon Gift Card $10 USD dùng mua hàng trên Amazon.com.", details: "• Giá trị: $10 USD\n• Dùng tại: Amazon.com\n• Giao ngay qua code\n• Không hết hạn", price: 260000, originalPrice: 280000, stock: 999, sold: 456, rating: 4.8, reviews: 189, featured: false, hot: false, active: true, game: "Amazon", image: "https://picsum.photos/seed/amazon-10/400/300", badge: null },
    { id: 151, categoryId: 8, name: "Thẻ Razer Gold - 200.000 VNĐ", description: "Razer Gold 200K, dùng nạp vào hàng trăm game hỗ trợ Razer Gold.", details: "• Mệnh giá: 200,000 VNĐ Razer Gold\n• Hỗ trợ: 100+ game\n• Giao ngay qua code\n• Không hết hạn", price: 210000, originalPrice: 220000, stock: 999, sold: 567, rating: 4.7, reviews: 234, featured: false, hot: false, active: true, game: "Razer Gold", image: "https://picsum.photos/seed/razer-gold/400/300", badge: null },
    { id: 152, categoryId: 8, name: "Thẻ Garena Free Fire - Nạp 200K", description: "Nạp 200K vào tài khoản Free Fire qua thẻ Garena trực tiếp.", details: "• Giá trị: 200,000 VNĐ\n• Game: Free Fire\n• Nhận: ~1100 Kim Cương\n• Giao ngay qua code", price: 205000, originalPrice: 210000, stock: 999, sold: 1567, rating: 4.9, reviews: 567, featured: true, hot: true, active: true, game: "Free Fire", image: "https://picsum.photos/seed/ff-200k/400/300", badge: "HOT" },
    { id: 153, categoryId: 8, name: "Voucher Lazada - 100K OFF", description: "Voucher giảm giá 100K khi mua trên Lazada, áp dụng nhiều danh mục.", details: "• Giảm: 100,000 VNĐ\n• Điều kiện: Đơn từ 200K\n• Hạn dùng: 30 ngày\n• Giao ngay qua code", price: 60000, originalPrice: 100000, stock: 200, sold: 890, rating: 4.5, reviews: 345, featured: false, hot: true, active: true, game: "Lazada", image: "https://picsum.photos/seed/lazada-vou/400/300", badge: "HOT" },
    { id: 154, categoryId: 8, name: "Voucher Shopee - 50K Freeship", description: "Voucher miễn phí vận chuyển Shopee 50K, áp dụng đơn hàng bất kỳ.", details: "• Loại: Freeship (50K)\n• Điều kiện: Không giới hạn\n• Hạn dùng: 14 ngày\n• Giao ngay qua code", price: 30000, originalPrice: 50000, stock: 500, sold: 2345, rating: 4.6, reviews: 890, featured: false, hot: false, active: true, game: "Shopee", image: "https://picsum.photos/seed/shopee-vou/400/300", badge: "SALE" },
    { id: 155, categoryId: 8, name: "Gift Card PSN PlayStation - $20", description: "PlayStation Store Gift Card $20, mua game và DLC trên PS4/PS5.", details: "• Giá trị: $20 USD\n• Dùng tại: PlayStation Store\n• Region: US\n• Giao ngay qua code\n• Không hết hạn", price: 500000, originalPrice: 560000, stock: 999, sold: 234, rating: 4.8, reviews: 98, featured: false, hot: false, active: true, game: "PlayStation", image: "https://picsum.photos/seed/psn-20/400/300", badge: null },
    { id: 156, categoryId: 8, name: "Microsoft Points Xbox - 1600 MP", description: "1600 Microsoft Points cho Xbox, mua DLC và game trên Xbox Store.", details: "• Giá trị: 1600 Microsoft Points\n• Dùng tại: Xbox Store\n• Giao ngay qua code\n• Không hết hạn", price: 300000, originalPrice: 380000, stock: 999, sold: 189, rating: 4.7, reviews: 78, featured: false, hot: false, active: true, game: "Xbox", image: "https://picsum.photos/seed/xbox-1600/400/300", badge: null },

    // ===== BỔ SUNG THÊM ĐA DẠNG =====
    { id: 157, categoryId: 1, name: "Nick Clash Royale - Arena 15 Max Deck", description: "Tài khoản Clash Royale Arena 15, deck max card, nhiều emote và tower skin.", details: "• Arena: Ultimate Champion\n• Card Max: 5 bộ\n• Trophy: 8000+\n• Tower Skin: 5\n• Emote: 20+\n• Bảo hành 7 ngày", price: 250000, originalPrice: 380000, stock: 7, sold: 89, rating: 4.7, reviews: 40, featured: false, hot: false, active: true, game: "Clash Royale", image: "https://picsum.photos/seed/cr-a15/400/300", badge: null },
    { id: 158, categoryId: 2, name: "Xclusive Money MLBB - 11000 Diamond", description: "11000 Diamond cực đại gói nhất cho Mobile Legends Bang Bang.", details: "• Số lượng: 11000 Diamond\n• Server: SEA\n• Nạp trực tiếp\n• Thời gian: 5-15 phút", price: 1100000, originalPrice: 1380000, stock: 999, sold: 234, rating: 4.9, reviews: 89, featured: true, hot: true, active: true, game: "Mobile Legends", image: "https://picsum.photos/seed/mlbb-11k/400/300", badge: "HOT" },
    { id: 159, categoryId: 3, name: "Bundle Fortnite - Festival Pass Max", description: "Festival Pass đã max level trong Fortnite, nhận toàn bộ cosmetic.", details: "• Pass: Fortnite Festival Pass Max\n• Level: 100/100\n• Reward: Tất cả skin + emote + guitar\n• Giao qua account", price: 200000, originalPrice: 300000, stock: 5, sold: 34, rating: 4.7, reviews: 18, featured: false, hot: false, active: true, game: "Fortnite", image: "https://picsum.photos/seed/fn-festival/400/300", badge: null },
    { id: 160, categoryId: 4, name: "Key Bitdefender Total Security - 2 Năm", description: "Bitdefender Total Security 2 năm bảo vệ 5 thiết bị, top antivirus 2024.", details: "• Phần mềm: Bitdefender Total Security\n• Thời hạn: 2 năm\n• Thiết bị: 5 PC/Mac/Android/iOS\n• Giao ngay qua email", price: 300000, originalPrice: 450000, stock: 999, sold: 267, rating: 4.8, reviews: 112, featured: false, hot: false, active: true, game: "Bitdefender", image: "https://picsum.photos/seed/bitdefender/400/300", badge: "SALE" },
    { id: 161, categoryId: 5, name: "Discord Server Boost x2 - 1 Tháng", description: "2 Server Boost Discord cho server của bạn, mở khóa Level 1.", details: "• Số lượng: 2 Server Boost\n• Thời hạn: 1 tháng\n• Level: Server Level 1\n• Giao ngay sau mua", price: 100000, originalPrice: 150000, stock: 999, sold: 345, rating: 4.6, reviews: 134, featured: false, hot: false, active: true, game: "Discord", image: "https://picsum.photos/seed/dc-boost2/400/300", badge: null },
    { id: 162, categoryId: 6, name: "Boost Rank Tốc Chiến Wild Rift - Plat → Master", description: "Boost Wild Rift từ Platinum lên Master với booster Pro Player.", details: "• Từ: Platinum I\n• Đến: Master\n• Thời gian: 5-7 ngày\n• Báo cáo mỗi ngày\n• Bảo mật VPN", price: 450000, originalPrice: 650000, stock: 8, sold: 56, rating: 4.8, reviews: 28, featured: true, hot: true, active: true, game: "Wild Rift", image: "https://picsum.photos/seed/wr-boost-plat/400/300", badge: "HOT" },
    { id: 163, categoryId: 7, name: "Tool Auto Comment YouTube & View", description: "Phần mềm tự động tăng view và comment YouTube từ tài khoản thật.", details: "• Tính năng: Auto view, auto comment, auto like\n• Account: Dùng tài khoản thật\n• Anti-spam: Delay ngẫu nhiên\n• Dashboard: Quản lý campaign\n• Bảo hành: 30 ngày hoạt động", price: 400000, originalPrice: 600000, stock: 999, sold: 145, rating: 4.3, reviews: 60, featured: false, hot: false, active: true, game: "YouTube Tool", image: "https://picsum.photos/seed/yt-tool/400/300", badge: null }
  ],
  orders: [
    { id: 1, date: "2024-01-15T10:30:00", customer: { name: "Nguyễn Văn An", email: "anvan@gmail.com", phone: "0912345678" }, items: [{ productId: 1, name: "Nick LMHT - Rank Kim Cương I", qty: 1, price: 250000 }], total: 250000, status: "completed", paymentMethod: "Momo" },
    { id: 2, date: "2024-01-15T11:15:00", customer: { name: "Trần Thị Bình", email: "binhtt@gmail.com", phone: "0987654321" }, items: [{ productId: 16, name: "Kim Cương Free Fire - 1000 KCM", qty: 2, price: 200000 }], total: 400000, status: "completed", paymentMethod: "Banking" },
    { id: 3, date: "2024-01-16T09:00:00", customer: { name: "Lê Hoàng Nam", email: "namhle@gmail.com", phone: "0901234567" }, items: [{ productId: 34, name: "Key Windows 11 Pro", qty: 1, price: 150000 }, { productId: 35, name: "Key Microsoft Office 365", qty: 1, price: 200000 }], total: 350000, status: "completed", paymentMethod: "Momo" },
    { id: 4, date: "2024-01-17T14:30:00", customer: { name: "Phạm Minh Tuấn", email: "tuanpm@gmail.com", phone: "0945678901" }, items: [{ productId: 7, name: "Nick Genshin Impact - AR55 Full 5★", qty: 1, price: 800000 }], total: 800000, status: "processing", paymentMethod: "Banking" },
    { id: 5, date: "2024-01-17T16:00:00", customer: { name: "Võ Thị Cẩm Tú", email: "tucv@gmail.com", phone: "0978901234" }, items: [{ productId: 48, name: "Boost LMHT - Vàng → Kim Cương", qty: 1, price: 500000 }], total: 500000, status: "processing", paymentMethod: "Momo" },
    { id: 6, date: "2024-01-18T08:45:00", customer: { name: "Đặng Quốc Hùng", email: "hungdq@gmail.com", phone: "0856789012" }, items: [{ productId: 19, name: "Robux Roblox - 2000 R$", qty: 1, price: 250000 }, { productId: 42, name: "Nick Facebook Clone", qty: 3, price: 50000 }], total: 400000, status: "completed", paymentMethod: "Banking" },
    { id: 7, date: "2024-01-18T10:30:00", customer: { name: "Hoàng Thị Mai", email: "maiht@gmail.com", phone: "0923456789" }, items: [{ productId: 41, name: "Netflix Premium - 1 Tháng", qty: 1, price: 90000 }], total: 90000, status: "completed", paymentMethod: "Momo" },
    { id: 8, date: "2024-01-19T13:00:00", customer: { name: "Bùi Văn Khoa", email: "khoabv@gmail.com", phone: "0934567890" }, items: [{ productId: 11, name: "Nick Clash of Clans - TH15 Max", qty: 1, price: 1200000 }], total: 1200000, status: "pending", paymentMethod: "Banking" },
    { id: 9, date: "2024-01-19T15:30:00", customer: { name: "Ngô Thị Lan", email: "lango@gmail.com", phone: "0867890123" }, items: [{ productId: 59, name: "Thẻ VCoin Garena - 500K", qty: 1, price: 510000 }, { productId: 20, name: "UC PUBG Mobile - 1875 UC", qty: 1, price: 300000 }], total: 810000, status: "completed", paymentMethod: "Momo" },
    { id: 10, date: "2024-01-20T09:15:00", customer: { name: "Đinh Văn Phúc", email: "phucdv@gmail.com", phone: "0878901234" }, items: [{ productId: 54, name: "Tool Auto Farm Game Mobile", qty: 1, price: 300000 }], total: 300000, status: "cancelled", paymentMethod: "Banking" }
  ]
};

// ===== Quản lý dữ liệu =====
function initData() {
  const raw = localStorage.getItem('mmo_data_v2');
  if (!raw) {
    localStorage.setItem('mmo_data_v2', JSON.stringify(INITIAL_DATA));
  } else {
    try {
      const existing = JSON.parse(raw);
      if (!existing.settings || existing.settings.nextProductId < 164) {
        localStorage.setItem('mmo_data_v2', JSON.stringify(INITIAL_DATA));
      } else {
        // Patch dữ liệu cũ thiếu field mới
        let changed = false;
        if (!existing.notifications) { existing.notifications = []; changed = true; }
        if (!existing.settings.nextNotificationId) { existing.settings.nextNotificationId = 1; changed = true; }
        if (existing.users) {
          existing.users.forEach(u => {
            if (u.balance === undefined) { u.balance = 0; changed = true; }
            if (!u.orderHistory) { u.orderHistory = []; changed = true; }
          });
        }
        if (changed) localStorage.setItem('mmo_data_v2', JSON.stringify(existing));
      }
    } catch(e) {
      localStorage.setItem('mmo_data_v2', JSON.stringify(INITIAL_DATA));
    }
  }
}
function getData() {
  const raw = localStorage.getItem('mmo_data_v2');
  return raw ? JSON.parse(raw) : INITIAL_DATA;
}
function saveData(data) {
  localStorage.setItem('mmo_data_v2', JSON.stringify(data));
}
function resetData() {
  localStorage.setItem('mmo_data_v2', JSON.stringify(INITIAL_DATA));
  return INITIAL_DATA;
}
initData();
